In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
processed_data_dir = os.path.join(project_path, 'data', 'processed_data')
processed_data_path = os.path.join(processed_data_dir, '02_processed_data.parquet')

In [3]:
df_processed = pl.read_parquet(processed_data_path)

In [4]:
df_processed.head()

shape: (5, 19)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ comment_id ┆ post_id ┆ comment_b ┆ comment_s ┆ … ┆ extractio ┆ extractio ┆ extractio ┆ text_cont │
│ ---        ┆ ---     ┆ ody       ┆ core      ┆   ┆ n_query   ┆ n_sort    ┆ n_time    ┆ ent       │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ str       ┆ i64       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ my7m6yl    ┆ 1ldbowi ┆ I don’t   ┆ 7         ┆ … ┆ ((gaza OR ┆ top       ┆ 2026-03-2 ┆ Post      │
│            ┆         ┆ hate you  ┆           ┆   ┆ palestine ┆           ┆ 6T10:09:0 ┆ Title:    │
│            ┆         ┆ as an     ┆           ┆   ┆ *) AND    ┆           ┆ 5.123482+ ┆           │
│            ┆         ┆ Israeli…  ┆           ┆   ┆ (med…     ┆           ┆ 00:…      ┆ I’m       │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Israeli,  │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ why …     │
│ n11hxav    ┆ 1lloezh ┆ Because   ┆ 3         ┆ … ┆ ((gaza OR ┆ top       ┆ 2026-03-2 ┆ Post      │
│            ┆         ┆ it isn't  ┆           ┆   ┆ palestine ┆           ┆ 6T10:09:0 ┆ Title:    │
│            ┆         ┆ one, a    ┆           ┆   ┆ *) AND    ┆           ┆ 5.123482+ ┆           │
│            ┆         ┆ genoci…   ┆           ┆   ┆ (gen…     ┆           ┆ 00:…      ┆ How can   │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ anyone    │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ st…       │
│ mu58xtn    ┆ 1ku8sal ┆ Even the  ┆ 1         ┆ … ┆ (gaza OR  ┆ comments  ┆ 2026-03-2 ┆ Post      │
│            ┆         ┆ stats on  ┆           ┆   ┆ palestine ┆           ┆ 6T10:09:0 ┆ Title:    │
│            ┆         ┆ it are    ┆           ┆   ┆ *)        ┆           ┆ 5.123482+ ┆           │
│            ┆         ┆ fake …    ┆           ┆   ┆           ┆           ┆ 00:…      ┆ No words  │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Post Bo…  │
│ n61xsyu    ┆ 1mdi98j ┆ Let me    ┆ -3        ┆ … ┆ ((gaza OR ┆ relevance ┆ 2026-03-2 ┆ Post      │
│            ┆         ┆ guess     ┆           ┆   ┆ palestine ┆           ┆ 6T10:09:0 ┆ Title:    │
│            ┆         ┆ John      ┆           ┆   ┆ *) AND    ┆           ┆ 5.123482+ ┆           │
│            ┆         ┆ Stewart   ┆           ┆   ┆ (bid…     ┆           ┆ 00:…      ┆ Jon       │
│            ┆         ┆ is H…     ┆           ┆   ┆           ┆           ┆           ┆ Stewart   │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ calle…    │
│ nndulce    ┆ 1opqxl5 ┆ Great! He ┆ 5         ┆ … ┆ (gaza OR  ┆ comments  ┆ 2026-03-2 ┆ Post      │
│            ┆         ┆ can fuck  ┆           ┆   ┆ palestine ┆           ┆ 6T10:09:0 ┆ Title:    │
│            ┆         ┆ off then, ┆           ┆   ┆ *)        ┆           ┆ 5.123482+ ┆           │
│            ┆         ┆ r…        ┆           ┆   ┆           ┆           ┆ 00:…      ┆ “I can no │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ longer …  │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
df_processed.shape

(237902, 19)

---

In [6]:
# 1. Mostrar el contenido completo de los strings (sin límite)
pl.Config.set_fmt_str_lengths(1000) # Ajusta al largo que necesites

polars.config.Config

In [7]:
df_processed.filter(
    pl.col('comment_id') == 'n8llnry'
)[['post_title', 'post_body', 'comment_body']]

shape: (1, 3)
┌───────────────────────────────────┬───────────────────────────────────────────────┬──────────────┐
│ post_title                        ┆ post_body                                     ┆ comment_body │
│ ---                               ┆ ---                                           ┆ ---          │
│ str                               ┆ str                                           ┆ str          │
╞═══════════════════════════════════╪═══════════════════════════════════════════════╪══════════════╡
│ Something everyone must agree is  ┆ Finally these kids have a chance.  Lets hope  ┆ Pallywood    │
│ amazing that is happening in Gaza ┆ it stays that way and peace with neighbours   ┆              │
│                                   ┆ could be a reality.                           ┆              │
└───────────────────────────────────┴───────────────────────────────────────────────┴──────────────┘