In [13]:
import os
import polars as pl

In [14]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
features_dir = os.path.join(project_path, 'data', 'features')
feature_file_path = os.path.join(features_dir, 'content_relevance_score.parquet')
feature_df = pl.read_parquet(feature_file_path)

In [15]:
# 1. Mostrar el contenido completo de los strings (sin límite)
pl.Config.set_fmt_str_lengths(1000) # Ajusta al largo que necesites

polars.config.Config

In [16]:
feature_df

shape: (238_002, 3)
┌────────────┬─────────────────────────┬───────────────────────────────────────────────────────────┐
│ comment_id ┆ content_relevance_score ┆ reasoning_content_relevance_score                         │
│ ---        ┆ ---                     ┆ ---                                                       │
│ str        ┆ i64                     ┆ str                                                       │
╞════════════╪═════════════════════════╪═══════════════════════════════════════════════════════════╡
│ mzlqxrg    ┆ 4                       ┆ The comment expresses a desire for Iran to take military  │
│            ┆                         ┆ action against Israel in the context of humanitarian aid, │
│            ┆                         ┆ which relates directly to the ongoing conflict and its    │
│            ┆                         ┆ implications for Gaza.                                    │
│ obbcoq3    ┆ 0                       ┆ The comment is vague and does not provide any specific    │
│            ┆                         ┆ information or opinion related to the Gaza conflict,      │
│            ┆                         ┆ focusing instead on a general statement about truth       │
│            ┆                         ┆ without context.                                          │
│ n9yjtzg    ┆ 2                       ┆ The comment reflects on the hostility faced by Jews in    │
│            ┆                         ┆ Barcelona, linking it to broader themes of antisemitism   │
│            ┆                         ┆ and public sentiment related to the Gaza conflict, but it │
│            ┆                         ┆ does not directly address the conflict itself or its core │
│            ┆                         ┆ events.                                                   │
│ nax2wzf    ┆ 1                       ┆ The comment focuses on a political strategy regarding the │
│            ┆                         ┆ Democratic Party in the context of the Gaza conflict, but │
│            ┆                         ┆ it does not directly address the humanitarian situation   │
│            ┆                         ┆ or the core events of the conflict itself. It is more     │
│            ┆                         ┆ about U.S. internal politics than the Gaza conflict.      │
│ n8vxcji    ┆ 3                       ┆ The comment reflects on a historical event related to     │
│            ┆                         ┆ Israel's actions in Gaza and connects it to current       │
│            ┆                         ┆ events, indicating a perspective on the conflict's        │
│            ┆                         ┆ implications. However, it does not engage with the core   │
│            ┆                         ┆ conflict or humanitarian issues directly.                 │
│ …          ┆ …                       ┆ …                                                         │
│ mqyllfc    ┆ 3                       ┆ The comment discusses the demographic composition of      │
│            ┆                         ┆ Israel and its political implications, which relates to   │
│            ┆                         ┆ the broader context of the Gaza conflict and the          │
│            ┆                         ┆ Israeli-Palestinian relations. However, it does not       │
│            ┆                         ┆ directly address the core conflict or humanitarian        │
│            ┆                         ┆ issues, making it less relevant.                          │
│ mraetks    ┆ 2                       ┆ The comment expresses a desire for the bakery to fail,    │
│            ┆                         ┆ which is a reaction to the violent slogans associated     │
│            ┆                         ┆ with the Israeli bakery. However, it does not engage with │
│            ┆                         ┆ the broader implications of the Gaza conflict or the      │
│            ┆                         ┆ humanitarian situation, making it less relevant to the    │
│            ┆                         ┆ core issues.                                              │
│ myg8mvn    ┆ 0                       ┆ The comment expresses appreciation for the original post  │
│            ┆                         ┆ but does not engage with the core issues of the Gaza      │
│            ┆                         ┆ conflict or provide any relevant insights, making it      │
│            ┆                         ┆ largely off-topic.                                        │
│ n0xoh1v    ┆ 3                       ┆ The comment discusses the perceived alliance between      │
│            ┆                         ┆ Islamists and the left in relation to Zionism, which      │
│            ┆                         ┆ touches on ideological perspectives related to the Gaza   │
│            ┆                         ┆ conflict but does not directly address the core issues or │
│            ┆                         ┆ events of the conflict itself.                            │
│ ndohlm4    ┆ 5                       ┆ The comment reflects on the actions of the IDF and raises │
│            ┆                         ┆ a moral question regarding their conduct, which is        │
│            ┆                         ┆ directly related to the core conflict and its             │
│            ┆                         ┆ humanitarian implications.                                │
└────────────┴─────────────────────────┴───────────────────────────────────────────────────────────┘

In [17]:
count_relevant_content = sum(feature_df['content_relevance_score'] >= 3) 
content_size = len(feature_df)
prop_relevant_content = count_relevant_content / content_size
print(f"Count relevant content: {count_relevant_content}")
print(f"Percentage relevant content: {round(prop_relevant_content * 100, 2)}%")

Count relevant content: 116850
Percentage relevant content: 49.1%

In [18]:
count_relevant_content = sum(feature_df['content_relevance_score'] >= 4) 
content_size = len(feature_df)
prop_relevant_content = count_relevant_content / content_size
print(f"Count relevant content: {count_relevant_content}")
print(f"Percentage relevant content: {round(prop_relevant_content * 100, 2)}%")

Count relevant content: 86956
Percentage relevant content: 36.54%

In [19]:
feature_df['content_relevance_score'].value_counts().sort('count', descending=True)

shape: (7, 2)
┌─────────────────────────┬───────┐
│ content_relevance_score ┆ count │
│ ---                     ┆ ---   │
│ i64                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ 4                       ┆ 55116 │
│ 0                       ┆ 53832 │
│ 2                       ┆ 39771 │
│ 5                       ┆ 31840 │
│ 3                       ┆ 29894 │
│ 1                       ┆ 27543 │
│ -1                      ┆ 6     │
└─────────────────────────┴───────┘

In [20]:
processed_data_dir = os.path.join(project_path, 'data', 'processed_data')

base_data_path = os.path.join(processed_data_dir, '02_processed_data.parquet') 

base_df = pl.read_parquet(base_data_path)

processed_df = base_df.join(feature_df, how='left', on='comment_id')

processed_df_filtered = processed_df[['comment_id', 'post_id', 'post_title', 'post_body', 'comment_body', 'content_relevance_score', 'reasoning_content_relevance_score']]

In [21]:
len(processed_df) - processed_df['content_relevance_score'].is_null().sum()

238002

In [22]:
processed_df['content_relevance_score'].is_null().sum()

0

In [23]:
for score in processed_df['content_relevance_score'].unique():
    print(f'content_relevance_score == {score}'.upper(), '\n')
    display(processed_df_filtered.filter(pl.col('content_relevance_score') == score).sample(n=5, seed=123))
    print('='*200, '\n')

CONTENT_RELEVANCE_SCORE == -1

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ n8mj7ql    ┆ 1mpr8o4 ┆ a video of    ┆              ┆ **Looks like ┆ -1           ┆ The comment  │
│            ┆         ┆ aljazera      ┆              ┆ this thread  ┆              ┆ is           │
│            ┆         ┆ journalist    ┆              ┆ is getting a ┆              ┆ meta-Reddit  │
│            ┆         ┆ Anas, who was ┆              ┆ lot of       ┆              ┆ moderation/a │
│            ┆         ┆ killed by     ┆              ┆ attention.   ┆              ┆ ttention (   │
│            ┆         ┆ Israel,       ┆              ┆ Greetings,   ┆              ┆              │
│            ┆         ┆ talking to    ┆              ┆ /r/all!      ┆              ┆              │
│            ┆         ┆ his daughter  ┆              ┆ Please keep  ┆              ┆              │
│            ┆         ┆ Sham.         ┆              ┆ it civil.**  ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆ *I am a bot, ┆              ┆              │
│            ┆         ┆               ┆              ┆ and this     ┆              ┆              │
│            ┆         ┆               ┆              ┆ action was   ┆              ┆              │
│            ┆         ┆               ┆              ┆ performed    ┆              ┆              │
│            ┆         ┆               ┆              ┆ automaticall ┆              ┆              │
│            ┆         ┆               ┆              ┆ y. Please    ┆              ┆              │
│            ┆         ┆               ┆              ┆ [contact the ┆              ┆              │
│            ┆         ┆               ┆              ┆ moderators   ┆              ┆              │
│            ┆         ┆               ┆              ┆ of this subr ┆              ┆              │
│            ┆         ┆               ┆              ┆ eddit](/mess ┆              ┆              │
│            ┆         ┆               ┆              ┆ age/compose/ ┆              ┆              │
│            ┆         ┆               ┆              ┆ ?to=/r/Pales ┆              ┆              │
│            ┆         ┆               ┆              ┆ tine) if you ┆              ┆              │
│            ┆         ┆               ┆              ┆ have any     ┆              ┆              │
│            ┆         ┆               ┆              ┆ questions or ┆              ┆              │
│            ┆         ┆               ┆              ┆ concerns.*   ┆              ┆              │
│ npf2aoc    ┆ 1ozxpc4 ┆ At least on   ┆              ┆ Something,   ┆ -1           ┆ The comment  │
│            ┆         ┆ Reddit,       ┆              ┆ something,   ┆              ┆ is a terse,  │
│            ┆         ┆ pro-Palestine ┆              ┆ projection   ┆              ┆ generic      │
│            ┆         ┆ subs do not   ┆              ┆ is the word  ┆              ┆ rebuttal (   │
│            ┆         ┆ say/discuss   ┆              ┆ that is      ┆              ┆              │
│            ┆         ┆ 'Globalize    ┆              ┆ appropriate  ┆              ┆              │
│            ┆         ┆ the Intifada' ┆              ┆ here.        ┆              ┆              │
│            ┆         ┆ much. But     ┆              ┆              ┆              ┆              │
│            ┆         ┆ pro-Israel    ┆              ┆              ┆              ┆              │
│            ┆         ┆ subs          ┆              ┆              ┆              ┆              │
│            ┆         ┆ absolutely do ┆              ┆              ┆              ┆              │
│            ┆         ┆ & obsess      ┆              ┆              ┆              ┆              │
│            ┆         ┆ about it. The ┆              ┆              ┆              ┆              │
│            ┆         ┆ 'controversy' ┆              ┆              ┆              ┆              │
│            ┆         ┆ over this     ┆              ┆              ┆              ┆              │
│            ┆         ┆ expression is ┆              ┆              ┆              ┆              │
│            ┆         ┆ exaggerated & ┆              ┆              ┆              ┆              │
│            ┆         ┆ weaponized to ┆              ┆              ┆              ┆              │
│            ┆         ┆ slander       ┆              ┆              ┆              ┆              │
│            ┆         ┆ critics of    ┆              ┆              ┆              ┆              │
│            ┆         ┆ Israel as     ┆              ┆              ┆              ┆              │
│            ┆         ┆ antisemitic.  ┆              ┆              ┆              ┆              │
│ ocakh06    ┆ 1s2nzvc ┆ I hope they   ┆ Infront of   ┆ Oh they      ┆ -1           ┆ Primary      │
│            ┆         ┆ realise the   ┆ Elstree and  ┆ realise      ┆              ┆ subject:     │
│            ┆         ┆ truth that    ┆ Borehamwood  ┆              ┆              ┆ accusation   │
│            ┆         ┆ they are      ┆ station,     ┆              ┆              ┆ of           │
│            ┆         ┆ supporting a  ┆ London, UK.  ┆              ┆              ┆ supporting a │
│            ┆         ┆ gncidl        ┆              ┆              ┆              ┆ 'genocidal   │
│            ┆         ┆ entity.       ┆              ┆              ┆              ┆ entity'      │
│            ┆         ┆               ┆              ┆              ┆              ┆ (core        │
│            ┆         ┆               ┆              ┆              ┆              ┆ Gaza/Israel  │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict) at │
│            ┆         ┆               ┆              ┆              ┆              ┆ a London     │
│            ┆         ┆               ┆              ┆              ┆              ┆ location;    │
│            ┆         ┆               ┆              ┆              ┆              ┆ the comment  │
│            ┆         ┆               ┆              ┆              ┆              ┆ (            │
│ n7xwa20    ┆ 1mm4i9x ┆ If Pro-Palest ┆ I often hear ┆ Couldn't     ┆ -1           ┆ The comment  │
│            ┆         ┆ inians think  ┆ Pro-Palestin ┆ agree more.  ┆              ┆ is a         │
│            ┆         ┆ "Zionism" is  ┆ ian say      ┆              ┆              ┆ one-line     │
│            ┆         ┆ an ideology   ┆ things like  ┆              ┆              ┆ expression   │
│            ┆         ┆ rather than a ┆ "I don't     ┆              ┆              ┆ of agreement │
│            ┆         ┆ reference to  ┆ hate Jews, I ┆              ┆              ┆ (            │
│            ┆         ┆ Jews, then    ┆ just hate    ┆              ┆              ┆              │
│            ┆         ┆ why do they   ┆ Zionists."   ┆              ┆              ┆              │
│            ┆         ┆ call all Jews ┆ They explain ┆              ┆              ┆              │
│            ┆         ┆ who moved to  ┆ that         ┆              ┆              ┆              │
│            ┆         ┆ Israel        ┆ "Zionists"   ┆              ┆              ┆              │
│            ┆         ┆ "Zionists"?   ┆ were a       ┆              ┆              ┆              │
│            ┆         ┆               ┆ political    ┆              ┆              ┆              │
│            ┆         ┆               ┆ movement to  ┆              ┆              ┆              │
│            ┆         ┆               ┆ displace     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Arabs or     ┆              ┆              ┆              │
│            ┆         ┆               ┆ something,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ totally      ┆              ┆              ┆              │
│            ┆         ┆               ┆ separate     ┆              ┆              ┆              │
│            ┆         ┆               ┆ from the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ ethnicity    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and religion ┆              ┆              ┆              │
│            ┆         ┆               ┆ of Judaism.  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ If that were ┆              ┆              ┆              │
│            ┆         ┆               ┆ true, then   ┆              ┆              ┆              │
│            ┆         ┆               ┆ why do they  ┆              ┆              ┆              │
│            ┆         ┆               ┆ call any     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jews who     ┆              ┆              ┆              │
│            ┆         ┆               ┆ moved to     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel       ┆              ┆              ┆              │
│            ┆         ┆               ┆ "Zionists"?  ┆              ┆              ┆              │
│            ┆         ┆               ┆ For          ┆              ┆              ┆              │
│            ┆         ┆               ┆ instance,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ they say     ┆              ┆              ┆              │
│            ┆         ┆               ┆ things like  ┆              ┆              ┆              │
│            ┆         ┆               ┆ "Hundreds of ┆              ┆              ┆              │
│            ┆         ┆               ┆ thousands of ┆              ┆              ┆              │
│            ┆         ┆               ┆ Zionist      ┆              ┆              ┆              │
│            ┆         ┆               ┆ colonizers   ┆              ┆              ┆              │
│            ┆         ┆               ┆ immigrated   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to Israel in ┆              ┆              ┆              │
│            ┆         ┆               ┆ the 1800s    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and 1900s"   ┆              ┆              ┆              │
│            ┆         ┆               ┆ even though  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the majority ┆              ┆              ┆              │
│            ┆         ┆               ┆ of Jews who  ┆              ┆              ┆              │
│            ┆         ┆               ┆ immigrated   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to Israel    ┆              ┆              ┆              │
│            ┆         ┆               ┆ were         ┆              ┆              ┆              │
│            ┆         ┆               ┆ refugees who ┆              ┆              ┆              │
│            ┆         ┆               ┆ had no       ┆              ┆              ┆              │
│            ┆         ┆               ┆ particular   ┆              ┆              ┆              │
│            ┆         ┆               ┆ political    ┆              ┆              ┆              │
│            ┆         ┆               ┆ agenda.      ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ There were   ┆              ┆              ┆              │
│            ┆         ┆               ┆ certainly    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jews who     ┆              ┆              ┆              │
│            ┆         ┆               ┆ dreamed of   ┆              ┆              ┆              │
│            ┆         ┆               ┆ some kind of ┆              ┆              ┆              │
│            ┆         ┆               ┆ vague        ┆              ┆              ┆              │
│            ┆         ┆               ┆ homeland in  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel —     ┆              ┆              ┆              │
│            ┆         ┆               ┆ originally   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the dream    ┆              ┆              ┆              │
│            ┆         ┆               ┆ was to be    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Ottoman      ┆              ┆              ┆              │
│            ┆         ┆               ┆ subjects     ┆              ┆              ┆              │
│            ┆         ┆               ┆ living in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the Ottoman  ┆              ┆              ┆              │
│            ┆         ┆               ┆ empire in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jewish neigh ┆              ┆              ┆              │
│            ┆         ┆               ┆ borhoods,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ later when   ┆              ┆              ┆              │
│            ┆         ┆               ┆ hundreds of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ groups       ┆              ┆              ┆              │
│            ┆         ┆               ┆ started      ┆              ┆              ┆              │
│            ┆         ┆               ┆ dreaming of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ a nation     ┆              ┆              ┆              │
│            ┆         ┆               ┆ state, Jews  ┆              ┆              ┆              │
│            ┆         ┆               ┆ did too —    ┆              ┆              ┆              │
│            ┆         ┆               ┆ but the      ┆              ┆              ┆              │
│            ┆         ┆               ┆ reality is,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ most Jews    ┆              ┆              ┆              │
│            ┆         ┆               ┆ moved to     ┆              ┆              ┆              │
│            ┆         ┆               ┆ escape       ┆              ┆              ┆              │
│            ┆         ┆               ┆ persecution. ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ For          ┆              ┆              ┆              │
│            ┆         ┆               ┆ instance, in ┆              ┆              ┆              │
│            ┆         ┆               ┆ the 1880s,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ most Jewish  ┆              ┆              ┆              │
│            ┆         ┆               ┆ immigrants   ┆              ┆              ┆              │
│            ┆         ┆               ┆ were Russian ┆              ┆              ┆              │
│            ┆         ┆               ┆ and Romanian ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jewih        ┆              ┆              ┆              │
│            ┆         ┆               ┆ refugees     ┆              ┆              ┆              │
│            ┆         ┆               ┆ fled pogroms ┆              ┆              ┆              │
│            ┆         ┆               ┆ (violent     ┆              ┆              ┆              │
│            ┆         ┆               ┆ anti-…       ┆              ┆              ┆              │
│ oaxrhwt    ┆ 1rw7k69 ┆ Mamdani rips  ┆              ┆ Mayor Shit-e ┆ -1           ┆ The comment  │
│            ┆         ┆ ‘genocide’ in ┆              ┆ ating-grin   ┆              ┆ is a short   │
│            ┆         ┆ Palestine at  ┆              ┆              ┆              ┆ insult/nickn │
│            ┆         ┆ St. Patrick’s ┆              ┆              ┆              ┆ ame (        │
│            ┆         ┆ Day event —   ┆              ┆              ┆              ┆              │
│            ┆         ┆ after he      ┆              ┆              ┆              ┆              │
│            ┆         ┆ botches       ┆              ┆              ┆              ┆              │
│            ┆         ┆ answer on     ┆              ┆              ┆              ┆              │
│            ┆         ┆ unified       ┆              ┆              ┆              ┆              │
│            ┆         ┆ Ireland       ┆              ┆              ┆              ┆              │
└────────────┴─────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 0

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ n7gnt3d    ┆ 1mk1sih ┆ Trump's       ┆              ┆ It is        ┆ 0            ┆ The comment  │
│            ┆         ┆ tariff war:   ┆              ┆ utterly      ┆              ┆ focuses on   │
│            ┆         ┆ Canada's      ┆              ┆ insane to    ┆              ┆ Canadian     │
│            ┆         ┆ sovereignty   ┆              ┆ suggest that ┆              ┆ public       │
│            ┆         ┆ is the real   ┆              ┆ the Canadian ┆              ┆ opinion      │
│            ┆         ┆ issue, trade  ┆              ┆ public would ┆              ┆ regarding    │
│            ┆         ┆ expert warns  ┆              ┆ accept       ┆              ┆ integration  │
│            ┆         ┆               ┆              ┆ greater      ┆              ┆ with the     │
│            ┆         ┆               ┆              ┆ integration  ┆              ┆ USA, which   │
│            ┆         ┆               ┆              ┆ with the     ┆              ┆ is unrelated │
│            ┆         ┆               ┆              ┆ USA,         ┆              ┆ to the Gaza  │
│            ┆         ┆               ┆              ┆ economic or  ┆              ┆ conflict and │
│            ┆         ┆               ┆              ┆ otherwise,   ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ in the       ┆              ┆ address any  │
│            ┆         ┆               ┆              ┆ current      ┆              ┆ relevant     │
│            ┆         ┆               ┆              ┆ context.     ┆              ┆ topics       │
│            ┆         ┆               ┆              ┆ People are   ┆              ┆ related to   │
│            ┆         ┆               ┆              ┆ extremely    ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆ angry with   ┆              ┆ conflict.    │
│            ┆         ┆               ┆              ┆ our          ┆              ┆              │
│            ┆         ┆               ┆              ┆ treacherous  ┆              ┆              │
│            ┆         ┆               ┆              ┆ former       ┆              ┆              │
│            ┆         ┆               ┆              ┆ friends.     ┆              ┆              │
│            ┆         ┆               ┆              ┆ This piece   ┆              ┆              │
│            ┆         ┆               ┆              ┆ totally      ┆              ┆              │
│            ┆         ┆               ┆              ┆ misses that  ┆              ┆              │
│ niuphe3    ┆ 1o38pai ┆ What are they ┆              ┆ They'll go   ┆ 0            ┆ The comment  │
│            ┆         ┆ going to do   ┆              ┆ back to      ┆              ┆ does not     │
│            ┆         ┆ now           ┆              ┆ gender       ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆ pronouns and ┆              ┆ Gaza         │
│            ┆         ┆               ┆              ┆ cancelling   ┆              ┆ conflict or  │
│            ┆         ┆               ┆              ┆ people who   ┆              ┆ any related  │
│            ┆         ┆               ┆              ┆ use the      ┆              ┆ topics,      │
│            ┆         ┆               ┆              ┆ wrong words. ┆              ┆ instead      │
│            ┆         ┆               ┆              ┆ You know, as ┆              ┆ focusing on  │
│            ┆         ┆               ┆              ┆ middle       ┆              ┆ social       │
│            ┆         ┆               ┆              ┆ school girls ┆              ┆ issues       │
│            ┆         ┆               ┆              ┆ do.          ┆              ┆ unrelated to │
│            ┆         ┆               ┆              ┆              ┆              ┆ the          │
│            ┆         ┆               ┆              ┆              ┆              ┆ situation in │
│            ┆         ┆               ┆              ┆              ┆              ┆ Gaza.        │
│ npbw28t    ┆ 1ozjb0c ┆ Will the US   ┆ Palestinian  ┆ Hi Dr_G_E,   ┆ 0            ┆ The comment  │
│            ┆         ┆ federal       ┆ President    ┆ **thank      ┆              ┆ is a bot-gen │
│            ┆         ┆ lawsuit filed ┆ Mahmoud      ┆ you** for    ┆              ┆ erated       │
│            ┆         ┆ last month    ┆ Abbas, who   ┆ posting in   ┆              ┆ response     │
│            ┆         ┆ against the   ┆ celebrated   ┆ our          ┆              ┆ that focuses │
│            ┆         ┆ PA and PLO    ┆ his 90th     ┆ community!   ┆              ┆ on subreddit │
│            ┆         ┆ result in the ┆ birthday on  ┆ Please check ┆              ┆ rules and    │
│            ┆         ┆ end of their  ┆ Saturday and ┆ if your post ┆              ┆ moderation,  │
│            ┆         ┆ use of mass   ┆ will begin   ┆ is rule 10   ┆              ┆ which does   │
│            ┆         ┆ murder of     ┆ the 22nd     ┆ and 11       ┆              ┆ not          │
│            ┆         ┆ civilians to  ┆ year of his  ┆ compliant.   ┆              ┆ contribute   │
│            ┆         ┆ "free         ┆ first 4-year ┆ Consider     ┆              ┆ to the       │
│            ┆         ┆ Palestine?"   ┆ term in      ┆ deleting     ┆              ┆ discussion   │
│            ┆         ┆               ┆ office next  ┆ immediately  ┆              ┆ about the    │
│            ┆         ┆               ┆ year, said   ┆ before there ┆              ┆ Gaza         │
│            ┆         ┆               ┆ in 2015 of   ┆ are comments ┆              ┆ conflict or  │
│            ┆         ┆               ┆ the wave of  ┆ if it is     ┆              ┆ public       │
│            ┆         ┆               ┆ Palestinian  ┆ not, but not ┆              ┆ opinion on   │
│            ┆         ┆               ┆ inspired     ┆ after (rule  ┆              ┆ it.          │
│            ┆         ┆               ┆ mass murders ┆ 12).         ┆              ┆              │
│            ┆         ┆               ┆ happening at ┆              ┆              ┆              │
│            ┆         ┆               ┆ that time in ┆ **Reminder   ┆              ┆              │
│            ┆         ┆               ┆ Israel, "We  ┆ to           ┆              ┆              │
│            ┆         ┆               ┆ said to      ┆ readers:**   ┆              ┆              │
│            ┆         ┆               ┆ everyone     ┆ All comments ┆              ┆              │
│            ┆         ┆               ┆ that we want ┆ need to      ┆              ┆              │
│            ┆         ┆               ┆ peaceful     ┆ abide by our ┆              ┆              │
│            ┆         ┆               ┆ popular      ┆ rules which  ┆              ┆              │
│            ┆         ┆               ┆ uprising,    ┆ are designed ┆              ┆              │
│            ┆         ┆               ┆ and that's   ┆ to maintain  ┆              ┆              │
│            ┆         ┆               ┆ what this    ┆ constructive ┆              ┆              │
│            ┆         ┆               ┆ is. That's   ┆ discourse.   ┆              ┆              │
│            ┆         ┆               ┆ what this    ┆ Please       ┆              ┆              │
│            ┆         ┆               ┆ is. However, ┆ review those ┆              ┆              │
│            ┆         ┆               ┆ the          ┆ rules if you ┆              ┆              │
│            ┆         ┆               ┆ aggression   ┆ are not      ┆              ┆              │
│            ┆         ┆               ┆ of firing    ┆ familiar     ┆              ┆              │
│            ┆         ┆               ┆ bullets has  ┆ with them,   ┆              ┆              │
│            ┆         ┆               ┆ come from    ┆ and remember ┆              ┆              │
│            ┆         ┆               ┆ the          ┆ to report    ┆              ┆              │
│            ┆         ┆               ┆ Israelis."   ┆ any comments ┆              ┆              │
│            ┆         ┆               ┆ The above    ┆ that violate ┆              ┆              │
│            ┆         ┆               ┆ from the     ┆ those        ┆              ┆              │
│            ┆         ┆               ┆ video of his ┆ guidelines.  ┆              ┆              │
│            ┆         ┆               ┆ speech       ┆              ┆              ┆              │
│            ┆         ┆               ┆ posted       ┆              ┆              ┆              │
│            ┆         ┆               ┆ earlier      ┆ *I am a bot, ┆              ┆              │
│            ┆         ┆               ┆ today on the ┆ and this     ┆              ┆              │
│            ┆         ┆               ┆ palwatch     ┆ action was   ┆              ┆              │
│            ┆         ┆               ┆ YouTube      ┆ performed    ┆              ┆              │
│            ┆         ┆               ┆ channel:     ┆ automaticall ┆              ┆              │
│            ┆         ┆               ┆ **Abbas:     ┆ y. Please    ┆              ┆              │
│            ┆         ┆               ┆ Murdering    ┆ [contact the ┆              ┆              │
│            ┆         ┆               ┆ Israelis is  ┆ moderators   ┆              ┆              │
│            ┆         ┆               ┆ popular      ┆ of this subr ┆              ┆              │
│            ┆         ┆               ┆ peaceful     ┆ eddit](/mess ┆              ┆              │
│            ┆         ┆               ┆ uprising**   ┆ age/compose/ ┆              ┆              │
│            ┆         ┆               ┆ Official PA  ┆ ?to=/r/Israe ┆              ┆              │
│            ┆         ┆               ┆ TV, Nov. 16, ┆ lPalestine)  ┆              ┆              │
│            ┆         ┆               ┆ 2015         ┆ if you have  ┆              ┆              │
│            ┆         ┆               ┆ Official PA  ┆ any          ┆              ┆              │
│            ┆         ┆               ┆ TV News      ┆ questions or ┆              ┆              │
│            ┆         ┆               ┆ broadcast    ┆ concerns.*   ┆              ┆              │
│            ┆         ┆               ┆ Excerpt from ┆              ┆              ┆              │
│            ┆         ┆               ┆ PA Chairman  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Mahmoud      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Abbas'       ┆              ┆              ┆              │
│            ┆         ┆               ┆ speech at    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ Palestine    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Prize        ┆              ┆              ┆              │
│            ┆         ┆               ┆ ceremony     ┆              ┆              ┆              │
│            ┆         ┆               ┆ PA Chairman  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Mahmoud      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Abbas: "No   ┆              ┆              ┆              │
│            ┆         ┆               ┆ one called   ┆              ┆              ┆              │
│            ┆         ┆               ┆ for this     ┆              ┆              ┆              │
│            ┆         ┆               ┆ uprising     ┆              ┆              ┆              │
│            ┆         ┆               ┆ (i.e., Oct.  ┆              ┆              ┆              │
│            ┆         ┆               ┆ - Nov. 2015  ┆              ┆              ┆              │
│            ┆         ┆               ┆ terror       ┆              ┆              ┆              │
│            ┆         ┆               ┆ campaign)    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and no one   ┆              ┆              ┆              │
│            ┆         ┆               ┆ asked for    ┆              ┆              ┆              │
│            ┆         ┆               ┆ it. It       ┆              ┆              ┆              │
│            ┆         ┆               ┆ stemmed from ┆              ┆              ┆              │
│            ┆         ┆               ┆ the hearts   ┆              ┆              ┆              │
│            ┆         ┆               ┆ of the young ┆              ┆              ┆              │
│            ┆         ┆               ┆ who have     ┆              ┆              ┆              │
│            ┆         ┆               ┆ seen         ┆              ┆              ┆              │
│            ┆         ┆               ┆ everything   ┆              ┆              ┆              │
│            ┆         ┆               ┆ with their   ┆              ┆              ┆              │
│            ┆         ┆               ┆ own eyes.    ┆              ┆              ┆              │
│            ┆         ┆               ┆ They have    ┆              ┆              ┆              │
│            ┆         ┆               ┆ seen the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ oppression,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ settlements  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and they     ┆              ┆              ┆              │
│            ┆         ┆               ┆ have seen…   ┆              ┆              ┆              │
│ ndum7w8    ┆ 1ne0r0x ┆ What a clown  ┆              ┆ Glad I never ┆ 0            ┆ The comment  │
│            ┆         ┆               ┆              ┆ liked        ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ Seinfeld now ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆ lol          ┆              ┆ Gaza         │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict or  │
│            ┆         ┆               ┆              ┆              ┆              ┆ any related  │
│            ┆         ┆               ┆              ┆              ┆              ┆ topics,      │
│            ┆         ┆               ┆              ┆              ┆              ┆ focusing     │
│            ┆         ┆               ┆              ┆              ┆              ┆ instead on a │
│            ┆         ┆               ┆              ┆              ┆              ┆ personal     │
│            ┆         ┆               ┆              ┆              ┆              ┆ opinion      │
│            ┆         ┆               ┆              ┆              ┆              ┆ about a      │
│            ┆         ┆               ┆              ┆              ┆              ┆ television   │
│            ┆         ┆               ┆              ┆              ┆              ┆ show, which  │
│            ┆         ┆               ┆              ┆              ┆              ┆ is           │
│            ┆         ┆               ┆              ┆              ┆              ┆ irrelevant   │
│            ┆         ┆               ┆              ┆              ┆              ┆ to the       │
│            ┆         ┆               ┆              ┆              ┆              ┆ study.       │
│ oa7rn8d    ┆ 1rsl9af ┆ my prediction ┆ you've all   ┆ Lol North    ┆ 0            ┆ The comment  │
│            ┆         ┆ for the recol ┆ called me    ┆ Korea? You   ┆              ┆ focuses on a │
│            ┆         ┆ onization of  ┆ crazy and    ┆ lost all     ┆              ┆ personal     │
│            ┆         ┆ america is    ┆ stupid for   ┆ credibility. ┆              ┆ attack       │
│            ┆         ┆ coming true.  ┆ thinking     ┆              ┆              ┆ regarding    │
│            ┆         ┆               ┆ that america ┆              ┆              ┆ credibility  │
│            ┆         ┆               ┆ is going to  ┆              ┆              ┆ and does not │
│            ┆         ┆               ┆ be           ┆              ┆              ┆ engage with  │
│            ┆         ┆               ┆ recolonized  ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ by the end   ┆              ┆              ┆ conflict or  │
│            ┆         ┆               ┆ of the       ┆              ┆              ┆ related      │
│            ┆         ┆               ┆ decade.      ┆              ┆              ┆ topics,      │
│            ┆         ┆               ┆ well, as     ┆              ┆              ┆ making it    │
│            ┆         ┆               ┆ with so many ┆              ┆              ┆ irrelevant   │
│            ┆         ┆               ┆ crazy people ┆              ┆              ┆ to the       │
│            ┆         ┆               ┆ in the past, ┆              ┆              ┆ study's      │
│            ┆         ┆               ┆ i'm being    ┆              ┆              ┆ focus.       │
│            ┆         ┆               ┆ proven       ┆              ┆              ┆              │
│            ┆         ┆               ┆ absolutely   ┆              ┆              ┆              │
│            ┆         ┆               ┆ right.       ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ america has  ┆              ┆              ┆              │
│            ┆         ┆               ┆ fucked with  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the wrong    ┆              ┆              ┆              │
│            ┆         ┆               ┆ country.     ┆              ┆              ┆              │
│            ┆         ┆               ┆ iran has     ┆              ┆              ┆              │
│            ┆         ┆               ┆ survived and ┆              ┆              ┆              │
│            ┆         ┆               ┆ it is        ┆              ┆              ┆              │
│            ┆         ┆               ┆ hopping mad. ┆              ┆              ┆              │
│            ┆         ┆               ┆ and, if      ┆              ┆              ┆              │
│            ┆         ┆               ┆ america      ┆              ┆              ┆              │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 1

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ mn0ogvj    ┆ 1jseg7e ┆ Israel admits ┆ Latest news  ┆ Israelis     ┆ 1            ┆ The comment  │
│            ┆         ┆ to killing    ┆ on the IDF   ┆ when they    ┆              ┆ does not     │
│            ┆         ┆ medics        ┆ killing      ┆ see a        ┆              ┆ directly     │
│            ┆         ┆               ┆ medics:      ┆ nursery      ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆              ┆              ┆ Gaza         │
│            ┆         ┆               ┆ *"The IDF    ┆ https://yout ┆              ┆ conflict or  │
│            ┆         ┆               ┆ has admitted ┆ u.be/OdFxa8E ┆              ┆ the events   │
│            ┆         ┆               ┆ to           ┆ WRT8?si=oeI_ ┆              ┆ surrounding  │
│            ┆         ┆               ┆ mistakenly   ┆ gb8802ut-QTo ┆              ┆ the IDF's    │
│            ┆         ┆               ┆ identifying  ┆              ┆              ┆ actions;     │
│            ┆         ┆               ┆ a convoy of  ┆ Sadly fair   ┆              ┆ instead, it  │
│            ┆         ┆               ┆ aid workers  ┆              ┆              ┆ appears to   │
│            ┆         ┆               ┆ as a threat  ┆              ┆              ┆ make a vague │
│            ┆         ┆               ┆ – following  ┆              ┆              ┆ reference to │
│            ┆         ┆               ┆ the          ┆              ┆              ┆ Israelis in  │
│            ┆         ┆               ┆ emergence of ┆              ┆              ┆ a            │
│            ┆         ┆               ┆ a video      ┆              ┆              ┆ non-specific │
│            ┆         ┆               ┆ which proved ┆              ┆              ┆ context,     │
│            ┆         ┆               ┆ their        ┆              ┆              ┆ which does   │
│            ┆         ┆               ┆ ambulances   ┆              ┆              ┆ not          │
│            ┆         ┆               ┆ were clearly ┆              ┆              ┆ contribute   │
│            ┆         ┆               ┆ marked when  ┆              ┆              ┆ to understan │
│            ┆         ┆               ┆ Israeli      ┆              ┆              ┆ ding public  │
│            ┆         ┆               ┆ troops       ┆              ┆              ┆ opinion on   │
│            ┆         ┆               ┆ opened fire  ┆              ┆              ┆ the          │
│            ┆         ┆               ┆ on them."*   ┆              ┆              ┆ conflict.    │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ *"An IDF     ┆              ┆              ┆              │
│            ┆         ┆               ┆ surveillance ┆              ┆              ┆              │
│            ┆         ┆               ┆ aircraft was ┆              ┆              ┆              │
│            ┆         ┆               ┆ watching the ┆              ┆              ┆              │
│            ┆         ┆               ┆ movement of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ ambulances   ┆              ┆              ┆              │
│            ┆         ┆               ┆ and notified ┆              ┆              ┆              │
│            ┆         ┆               ┆ troops on    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the ground.  ┆              ┆              ┆              │
│            ┆         ┆               ┆ The IDF said ┆              ┆              ┆              │
│            ┆         ┆               ┆ it will not  ┆              ┆              ┆              │
│            ┆         ┆               ┆ be releasing ┆              ┆              ┆              │
│            ┆         ┆               ┆ that         ┆              ┆              ┆              │
│            ┆         ┆               ┆ footage."*   ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ *"The IDF    ┆              ┆              ┆              │
│            ┆         ┆               ┆ also         ┆              ┆              ┆              │
│            ┆         ┆               ┆ acknowledged ┆              ┆              ┆              │
│            ┆         ┆               ┆ it was       ┆              ┆              ┆              │
│            ┆         ┆               ┆ previously   ┆              ┆              ┆              │
│            ┆         ┆               ┆ incorrect in ┆              ┆              ┆              │
│            ┆         ┆               ┆ its last     ┆              ┆              ┆              │
│            ┆         ┆               ┆ statement    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and that the ┆              ┆              ┆              │
│            ┆         ┆               ┆ ambulances   ┆              ┆              ┆              │
│            ┆         ┆               ┆ had their    ┆              ┆              ┆              │
│            ┆         ┆               ┆ lights on    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and 'were    ┆              ┆              ┆              │
│            ┆         ┆               ┆ clearly iden ┆              ┆              ┆              │
│            ┆         ┆               ┆ tifiable'.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ They have    ┆              ┆              ┆              │
│            ┆         ┆               ┆ since said   ┆              ┆              ┆              │
│            ┆         ┆               ┆ they are     ┆              ┆              ┆              │
│            ┆         ┆               ┆ launching a  ┆              ┆              ┆              │
│            ┆         ┆               ┆ probe into   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the discrepa ┆              ┆              ┆              │
│            ┆         ┆               ┆ ncy."*       ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ *"They also  ┆              ┆              ┆              │
│            ┆         ┆               ┆ added that   ┆              ┆              ┆              │
│            ┆         ┆               ┆ aid workers  ┆              ┆              ┆              │
│            ┆         ┆               ┆ being buried ┆              ┆              ┆              │
│            ┆         ┆               ┆ in a mass    ┆              ┆              ┆              │
│            ┆         ┆               ┆ grave was a  ┆              ┆              ┆              │
│            ┆         ┆               ┆ regular      ┆              ┆              ┆              │
│            ┆         ┆               ┆ practice     ┆              ┆              ┆              │
│            ┆         ┆               ┆ '...to       ┆              ┆              ┆              │
│            ┆         ┆               ┆ prevent wild ┆              ┆              ┆              │
│            ┆         ┆               ┆ dogs and     ┆              ┆              ┆              │
│            ┆         ┆               ┆ other        ┆              ┆              ┆              │
│            ┆         ┆               ┆ animals from ┆              ┆              ┆              │
│            ┆         ┆               ┆ eating the   ┆              ┆              ┆              │
│            ┆         ┆               ┆ corpses.'"*  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Seems like   ┆              ┆              ┆              │
│            ┆         ┆               ┆ every point  ┆              ┆              ┆              │
│            ┆         ┆               ┆ that was     ┆              ┆              ┆              │
│            ┆         ┆               ┆ raised in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ defence of   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the IDF in   ┆              ┆              ┆              │
│            ┆         ┆               ┆ this         ┆              ┆              ┆              │
│            ┆         ┆               ┆ subreddit    ┆              ┆              ┆              │
│            ┆         ┆               ┆ was          ┆              ┆              ┆              │
│            ┆         ┆               ┆ nonsense.    ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ So, looking  ┆              ┆              ┆              │
│            ┆         ┆               ┆ at these     ┆              ┆              ┆              │
│            ┆         ┆               ┆ statements:  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ 1. The IDF   ┆              ┆              ┆              │
│            ┆         ┆               ┆ knew the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ convoy was   ┆              ┆              ┆              │
│            ┆         ┆               ┆ coming and   ┆              ┆              ┆              │
│            ┆         ┆               ┆ still opened ┆              ┆              ┆              │
│            ┆         ┆               ┆ fire.        ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ 2.…          ┆              ┆              ┆              │
│ my8ezxi    ┆ 1ld9k66 ┆ What do you   ┆ [https://x.c ┆ I don't      ┆ 1            ┆ The comment  │
│            ┆         ┆ think of      ┆ om/TrumpDail ┆ think        ┆              ┆ primarily    │
│            ┆         ┆ Trump         ┆ yPosts/statu ┆ America      ┆              ┆ discusses    │
│            ┆         ┆ breaking with ┆ s/1934752874 ┆ should have  ┆              ┆ U.S.         │
│            ┆         ┆ Tucker        ┆ 984018176?t= ┆ boots on the ┆              ┆ military     │
│            ┆         ┆ Carlson on    ┆ plT4yfG1zlj7 ┆ ground for   ┆              ┆ involvement  │
│            ┆         ┆ Iran?         ┆ FKSTg2qHVA&s ┆ either       ┆              ┆ in foreign   │
│            ┆         ┆               ┆ =19](https:/ ┆ Ukraine or   ┆              ┆ conflicts,   │
│            ┆         ┆               ┆ /x.com/Trump ┆ Iran. I      ┆              ┆ specifically │
│            ┆         ┆               ┆ DailyPosts/s ┆ don't even   ┆              ┆ mentioning   │
│            ┆         ┆               ┆ tatus/193475 ┆ think we     ┆              ┆ Ukraine and  │
│            ┆         ┆               ┆ 287498401817 ┆ should       ┆              ┆ Iran, but    │
│            ┆         ┆               ┆ 6?t=plT4yfG1 ┆ subsidized   ┆              ┆ does not     │
│            ┆         ┆               ┆ zlj7FKSTg2qH ┆ either       ┆              ┆ directly     │
│            ┆         ┆               ┆ VA&s=19)     ┆ country. The ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆ only country ┆              ┆ Gaza         │
│            ┆         ┆               ┆ [https://the ┆ right now    ┆              ┆ conflict or  │
│            ┆         ┆               ┆ hill.com/hom ┆ where I      ┆              ┆ its related  │
│            ┆         ┆               ┆ enews/admini ┆ would be     ┆              ┆ issues,      │
│            ┆         ┆               ┆ stration/535 ┆ okay with    ┆              ┆ making it    │
│            ┆         ┆               ┆ 3448-trump-s ┆ American     ┆              ┆ largely      │
│            ┆         ┆               ┆ wipes-at-tuc ┆ getting      ┆              ┆ off-topic.   │
│            ┆         ┆               ┆ ker-carlson- ┆ involved     ┆              ┆              │
│            ┆         ┆               ┆ over-israel- ┆ even if they ┆              ┆              │
│            ┆         ┆               ┆ iran-critici ┆ weren't a    ┆              ┆              │
│            ┆         ┆               ┆ sm/](https:/ ┆ party to is  ┆              ┆              │
│            ┆         ┆               ┆ /thehill.com ┆ Taiwan. As   ┆              ┆              │
│            ┆         ┆               ┆ /homenews/ad ┆ that is the  ┆              ┆              │
│            ┆         ┆               ┆ ministration ┆ only place   ┆              ┆              │
│            ┆         ┆               ┆ /5353448-tru ┆ with         ┆              ┆              │
│            ┆         ┆               ┆ mp-swipes-at ┆ strategic    ┆              ┆              │
│            ┆         ┆               ┆ -tucker-carl ┆ necessity    ┆              ┆              │
│            ┆         ┆               ┆ son-over-isr ┆ out of all   ┆              ┆              │
│            ┆         ┆               ┆ ael-iran-cri ┆ of them.     ┆              ┆              │
│            ┆         ┆               ┆ ticism/)     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Personally,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ I just think ┆              ┆              ┆              │
│            ┆         ┆               ┆ Trump is     ┆              ┆              ┆              │
│            ┆         ┆               ┆ getting      ┆              ┆              ┆              │
│            ┆         ┆               ┆ worse with   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ nicknames. I ┆              ┆              ┆              │
│            ┆         ┆               ┆ mean, Tehran ┆              ┆              ┆              │
│            ┆         ┆               ┆ Tucker was   ┆              ┆              ┆              │
│            ┆         ┆               ┆ right there  ┆              ┆              ┆              │
│ nriy2bl    ┆ 1pag3qu ┆ Political     ┆ PM files     ┆ I think they ┆ 1            ┆ The comment  │
│            ┆         ┆ earthquake:   ┆ 14-page      ┆ should       ┆              ┆ focuses on   │
│            ┆         ┆ Netanyahu     ┆ clemency     ┆ pardon him   ┆              ┆ Netanyahu's  │
│            ┆         ┆ submits       ┆ petition to  ┆ on the       ┆              ┆ political    │
│            ┆         ┆ pardon        ┆ president’s  ┆ condition    ┆              ┆ situation    │
│            ┆         ┆ request to    ┆ legal team,  ┆ that he      ┆              ┆ and          │
│            ┆         ┆ President     ┆ arguing      ┆ doesn't run  ┆              ┆ potential    │
│            ┆         ┆ Herzog        ┆ 'public      ┆ again in the ┆              ┆ future       │
│            ┆         ┆               ┆ interest'    ┆ next         ┆              ┆ elections,   │
│            ┆         ┆               ┆ warrants     ┆ election.    ┆              ┆ which are    │
│            ┆         ┆               ┆ stopping his ┆ Yeah, he     ┆              ┆ not directly │
│            ┆         ┆               ┆ corruption   ┆ doesn't      ┆              ┆ related to   │
│            ┆         ┆               ┆ trial, while ┆ deserve      ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ insisting he ┆ that, but it ┆              ┆ conflict or  │
│            ┆         ┆               ┆ bears no     ┆ would be     ┆              ┆ public       │
│            ┆         ┆               ┆ guilt and    ┆ better for   ┆              ┆ opinion on   │
│            ┆         ┆               ┆ offering no  ┆ the country. ┆              ┆ it.          │
│            ┆         ┆               ┆ remorse      ┆              ┆              ┆              │
│ n2esfk1    ┆ 1lwgse0 ┆ New Admission ┆ \*\*         ┆ so?          ┆ 1            ┆ The comment  │
│            ┆         ┆ of Apartheid  ┆ Edit: A lot  ┆              ┆              ┆ dismisses    │
│            ┆         ┆ Just Dropped  ┆ of people    ┆ of course    ┆              ┆ the          │
│            ┆         ┆               ┆ seem not to  ┆ the priority ┆              ┆ discussion   │
│            ┆         ┆               ┆ realize:     ┆ is to        ┆              ┆ of police    │
│            ┆         ┆               ┆ according to ┆ protect the  ┆              ┆ priorities   │
│            ┆         ┆               ┆ the current  ┆ jews in the  ┆              ┆ in the West  │
│            ┆         ┆               ┆ agreements   ┆ west bank,   ┆              ┆ Bank and     │
│            ┆         ┆               ┆ in place,    ┆ unlike       ┆              ┆ shifts focus │
│            ┆         ┆               ┆ all policing ┆ paliwood     ┆              ┆ to a         │
│            ┆         ┆               ┆ in Area C    ┆ propaganda,  ┆              ┆ defensive    │
│            ┆         ┆               ┆ (which       ┆ they are     ┆              ┆ stance       │
│            ┆         ┆               ┆ constitutes  ┆ ones         ┆              ┆ regarding    │
│            ┆         ┆               ┆ the majority ┆ constantly   ┆              ┆ Israeli      │
│            ┆         ┆               ┆ of the West  ┆ under attack ┆              ┆ settlers,    │
│            ┆         ┆               ┆ Bank by      ┆ by the       ┆              ┆ which does   │
│            ┆         ┆               ┆ area) is     ┆ Palestinians ┆              ┆ not engage   │
│            ┆         ┆               ┆ conducted by ┆              ┆              ┆ with the     │
│            ┆         ┆               ┆ the Israeli  ┆              ┆              ┆ core issues  │
│            ┆         ┆               ┆ police. In   ┆              ┆              ┆ of the Gaza  │
│            ┆         ┆               ┆ all legal    ┆              ┆              ┆ conflict or  │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 2

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ ngk4osa    ┆ 1nq7uoy ┆ Protesters    ┆              ┆ The Free     ┆ 2            ┆ The comment  │
│            ┆         ┆ disrupt       ┆              ┆ Palestine    ┆              ┆ critiques    │
│            ┆         ┆ Kamala        ┆              ┆ movement is  ┆              ┆ the Free     │
│            ┆         ┆ Harris' first ┆              ┆ an           ┆              ┆ Palestine    │
│            ┆         ┆ stop on book  ┆              ┆ incoherant   ┆              ┆ movement and │
│            ┆         ┆ tour over     ┆              ┆ mess. It     ┆              ┆ its          │
│            ┆         ┆ Gaza          ┆              ┆ makes        ┆              ┆ perceived    │
│            ┆         ┆               ┆              ┆ excuses for  ┆              ┆ contradictio │
│            ┆         ┆               ┆              ┆ terrorism.   ┆              ┆ ns, but it   │
│            ┆         ┆               ┆              ┆ Its          ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ left-wing    ┆              ┆ engage with  │
│            ┆         ┆               ┆              ┆ but tells us ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆ which        ┆              ┆ issues of    │
│            ┆         ┆               ┆              ┆ countries    ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆ can exist.   ┆              ┆ conflict     │
│            ┆         ┆               ┆              ┆ They were    ┆              ┆ itself,      │
│            ┆         ┆               ┆              ┆ celebrating  ┆              ┆ focusing     │
│            ┆         ┆               ┆              ┆ in all over  ┆              ┆ instead on   │
│            ┆         ┆               ┆              ┆ the world    ┆              ┆ the          │
│            ┆         ┆               ┆              ┆ from         ┆              ┆ movement's   │
│            ┆         ┆               ┆              ┆ Australia to ┆              ┆ actions and  │
│            ┆         ┆               ┆              ┆ New York on  ┆              ┆ ideology.    │
│            ┆         ┆               ┆              ┆ October 8th. ┆              ┆              │
│ n6auunj    ┆ 1meduir ┆ Jewish        ┆ The          ┆ Imagine if   ┆ 2            ┆ The comment  │
│            ┆         ┆ LGBTQ2+ group ┆ organizers   ┆ they asked   ┆              ┆ draws a      │
│            ┆         ┆ excluded from ┆ took issue   ┆ Sino-Canadia ┆              ┆ parallel     │
│            ┆         ┆ Montreal      ┆ with the     ┆ ns to        ┆              ┆ between the  │
│            ┆         ┆ Pride         ┆ groups       ┆ dissociate   ┆              ┆ expectations │
│            ┆         ┆               ┆ connection   ┆ from the     ┆              ┆ placed on    │
│            ┆         ┆               ┆ to the CIJA, ┆ Chinese      ┆              ┆ Jewish       │
│            ┆         ┆               ┆ which is one ┆ government   ┆              ┆ individuals  │
│            ┆         ┆               ┆ of the main  ┆              ┆              ┆ regarding    │
│            ┆         ┆               ┆ Jewish orgs  ┆              ┆              ┆ their        │
│            ┆         ┆               ┆ in Canada,   ┆              ┆              ┆ connection   │
│            ┆         ┆               ┆ who are      ┆              ┆              ┆ to Israel    │
│            ┆         ┆               ┆ pretty much  ┆              ┆              ┆ and the      │
│            ┆         ┆               ┆ connected to ┆              ┆              ┆ hypothetical │
│            ┆         ┆               ┆ every major  ┆              ┆              ┆ expectation  │
│            ┆         ┆               ┆ Jewish       ┆              ┆              ┆ on Sino-Cana │
│            ┆         ┆               ┆ community    ┆              ┆              ┆ dians to     │
│            ┆         ┆               ┆ group and    ┆              ┆              ┆ dissociate   │
│            ┆         ┆               ┆ initiative.  ┆              ┆              ┆ from the     │
│            ┆         ┆               ┆              ┆              ┆              ┆ Chinese      │
│            ┆         ┆               ┆ This         ┆              ┆              ┆ government.  │
│            ┆         ┆               ┆ standard of  ┆              ┆              ┆ While it     │
│            ┆         ┆               ┆ expecting    ┆              ┆              ┆ touches on   │
│            ┆         ┆               ┆ Jews to      ┆              ┆              ┆ broader      │
│            ┆         ┆               ┆ divest from  ┆              ┆              ┆ themes of    │
│            ┆         ┆               ┆ any and all  ┆              ┆              ┆ identity and │
│            ┆         ┆               ┆ connection   ┆              ┆              ┆ community,   │
│            ┆         ┆               ┆ to Israel is ┆              ┆              ┆ it does not  │
│            ┆         ┆               ┆ impossible   ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆ to meet.     ┆              ┆              ┆ address the  │
│            ┆         ┆               ┆ There is no  ┆              ┆              ┆ Gaza         │
│            ┆         ┆               ┆ possible way ┆              ┆              ┆ conflict or  │
│            ┆         ┆               ┆ to do so     ┆              ┆              ┆ its core     │
│            ┆         ┆               ┆ without      ┆              ┆              ┆ issues.      │
│            ┆         ┆               ┆ abandoning   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ community. I ┆              ┆              ┆              │
│            ┆         ┆               ┆ think that   ┆              ┆              ┆              │
│            ┆         ┆               ┆ most         ┆              ┆              ┆              │
│            ┆         ┆               ┆ non-Jews do  ┆              ┆              ┆              │
│            ┆         ┆               ┆ not really   ┆              ┆              ┆              │
│            ┆         ┆               ┆ understand   ┆              ┆              ┆              │
│            ┆         ┆               ┆ why a tiny   ┆              ┆              ┆              │
│            ┆         ┆               ┆ stip of land ┆              ┆              ┆              │
│            ┆         ┆               ┆ where almost ┆              ┆              ┆              │
│            ┆         ┆               ┆ half of all  ┆              ┆              ┆              │
│            ┆         ┆               ┆ of us live   ┆              ┆              ┆              │
│            ┆         ┆               ┆ would be     ┆              ┆              ┆              │
│            ┆         ┆               ┆ seen as      ┆              ┆              ┆              │
│            ┆         ┆               ┆ important.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ It's where   ┆              ┆              ┆              │
│            ┆         ┆               ┆ our families ┆              ┆              ┆              │
│            ┆         ┆               ┆ are, it's    ┆              ┆              ┆              │
│            ┆         ┆               ┆ where our    ┆              ┆              ┆              │
│            ┆         ┆               ┆ history is,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ it's where   ┆              ┆              ┆              │
│            ┆         ┆               ┆ our          ┆              ┆              ┆              │
│            ┆         ┆               ┆ community    ┆              ┆              ┆              │
│            ┆         ┆               ┆ members are  ┆              ┆              ┆              │
│            ┆         ┆               ┆ from, the    ┆              ┆              ┆              │
│            ┆         ┆               ┆ people in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ our shuls,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ our camps,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ our          ┆              ┆              ┆              │
│            ┆         ┆               ┆ daycares,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ our          ┆              ┆              ┆              │
│            ┆         ┆               ┆ schools..    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Completely   ┆              ┆              ┆              │
│            ┆         ┆               ┆ divesting    ┆              ┆              ┆              │
│            ┆         ┆               ┆ from anyone  ┆              ┆              ┆              │
│            ┆         ┆               ┆ who supports ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ existence of ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel means ┆              ┆              ┆              │
│            ┆         ┆               ┆ severing     ┆              ┆              ┆              │
│            ┆         ┆               ┆ ties with    ┆              ┆              ┆              │
│            ┆         ┆               ┆ nearly       ┆              ┆              ┆              │
│            ┆         ┆               ┆ everyone.    ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ It           ┆              ┆              ┆              │
│            ┆         ┆               ┆ absolutely   ┆              ┆              ┆              │
│            ┆         ┆               ┆ feels like   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ expectation  ┆              ┆              ┆              │
│            ┆         ┆               ┆ for Jews is  ┆              ┆              ┆              │
│            ┆         ┆               ┆ now to       ┆              ┆              ┆              │
│            ┆         ┆               ┆ abandon      ┆              ┆              ┆              │
│            ┆         ┆               ┆ their        ┆              ┆              ┆              │
│            ┆         ┆               ┆ family,      ┆              ┆              ┆              │
│            ┆         ┆               ┆ their        ┆              ┆              ┆              │
│            ┆         ┆               ┆ friends, and ┆              ┆              ┆              │
│            ┆         ┆               ┆ their        ┆              ┆              ┆              │
│            ┆         ┆               ┆ community.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Even if they ┆              ┆              ┆              │
│            ┆         ┆               ┆ may care     ┆              ┆              ┆              │
│            ┆         ┆               ┆ about Palest ┆              ┆              ┆              │
│            ┆         ┆               ┆ inians, even ┆              ┆              ┆              │
│            ┆         ┆               ┆ if they may  ┆              ┆              ┆              │
│            ┆         ┆               ┆ support a    ┆              ┆              ┆              │
│            ┆         ┆               ┆ two-state    ┆              ┆              ┆              │
│            ┆         ┆               ┆ solution, or ┆              ┆              ┆              │
│            ┆         ┆               ┆ fi…          ┆              ┆              ┆              │
│ ngu0m5z    ┆ 1ntjhen ┆ They opened a ┆ I thought it ┆ Hamas        ┆ 2            ┆ The comment  │
│            ┆         ┆ Nutella       ┆ was the      ┆ members only ┆              ┆ references   │
│            ┆         ┆ Restaurant in ┆ worst famine ┆ must show    ┆              ┆ Hamas in a   │
│            ┆         ┆ Gaza? How is  ┆ of the       ┆ green        ┆              ┆ context that │
│            ┆         ┆ this          ┆ century. So  ┆ headband.    ┆              ┆ implies a    │
│            ┆         ┆ possible?     ┆ how is it    ┆              ┆              ┆ connection   │
│            ┆         ┆               ┆ possible     ┆              ┆              ┆ to the       │
│            ┆         ┆               ┆ that a       ┆              ┆              ┆ situation in │
│            ┆         ┆               ┆ restaurant   ┆              ┆              ┆ Gaza, but it │
│            ┆         ┆               ┆ selling      ┆              ┆              ┆ does not     │
│            ┆         ┆               ┆ Nutella is   ┆              ┆              ┆ provide      │
│            ┆         ┆               ┆ opening in   ┆              ┆              ┆ substantial  │
│            ┆         ┆               ┆ the Gaza     ┆              ┆              ┆ insight into │
│            ┆         ┆               ┆ Strip?       ┆              ┆              ┆ the conflict │
│            ┆         ┆               ┆              ┆              ┆              ┆ or public    │
│            ┆         ┆               ┆ [https://x.c ┆              ┆              ┆ opinion      │
│            ┆         ┆               ┆ om/TheJewish ┆              ┆              ┆ regarding    │
│            ┆         ┆               ┆ Ally/status/ ┆              ┆              ┆ it. It is    │
│            ┆         ┆               ┆ 196675045754 ┆              ┆              ┆ more of a    │
│            ┆         ┆               ┆ 5503068/vide ┆              ┆              ┆ trivial      │
│            ┆         ┆               ┆ o/1](https:/ ┆              ┆              ┆ remark than  │
│            ┆         ┆               ┆ /x.com/TheJe ┆              ┆              ┆ a meaningful │
│            ┆         ┆               ┆ wishAlly/sta ┆              ┆              ┆ contribution │
│            ┆         ┆               ┆ tus/19667504 ┆              ┆              ┆ to the       │
│            ┆         ┆               ┆ 57545503068/ ┆              ┆              ┆ discussion.  │
│            ┆         ┆               ┆ video/1)     ┆              ┆              ┆              │
│ nwi6fvr    ┆ 1pyerf9 ┆ People losing ┆ I am trying  ┆ ap news      ┆ 2            ┆ The comment  │
│            ┆         ┆ their minds   ┆ to figure    ┆ reported     ┆              ┆ primarily    │
│            ┆         ┆ over Israel   ┆ out the      ┆ that the     ┆              ┆ discusses    │
│            ┆         ┆ recognizing   ┆ reason why   ┆ somaliland   ┆              ┆ the          │
│            ┆         ┆ Somaliland    ┆ are people   ┆ recognition  ┆              ┆ recognition  │
│            ┆         ┆ proves (for   ┆ obsessed     ┆ is so 1      ┆              ┆ of           │
│            ┆         ┆ the 1000th    ┆ about making ┆ million      ┆              ┆ Somaliland   │
│            ┆         ┆ time) that    ┆ Palestine a  ┆ gazans can   ┆              ┆ by Israel in │
│            ┆         ┆ leftists      ┆ country but  ┆ be           ┆              ┆ the context  │
│            ┆         ┆ don't really  ┆ are mad when ┆ ethnically   ┆              ┆ of the Gaza  │
│            ┆         ┆ care about    ┆ Israel       ┆ cleansed and ┆              ┆ conflict,    │
│            ┆         ┆ anyone, they  ┆ recognizes   ┆ moved to     ┆              ┆ but it does  │
│            ┆         ┆ just hate the ┆ Somaliland   ┆ somaliland   ┆              ┆ so through a │
│            ┆         ┆ Jews          ┆ as a country ┆ \-----       ┆              ┆ lens of anti │
│            ┆         ┆               ┆              ┆              ┆              ┆ -Palestinian │
│            ┆         ┆               ┆ Like, when   ┆ Since 1948,  ┆              ┆ sentiment    │
│            ┆         ┆               ┆ we compare   ┆ US support   ┆              ┆ and broader  │
│            ┆         ┆               ┆ them, we     ┆ for Israel   ┆              ┆ ideological  │
│            ┆         ┆               ┆ have on one  ┆ has been     ┆              ┆ arguments,   │
│            ┆         ┆               ┆ end          ┆ immoral,     ┆              ┆ which        │
│            ┆         ┆               ┆ Palestine    ┆ leading to   ┆              ┆ detracts     │
│            ┆         ┆               ┆ which is a   ┆ the Iraq and ┆              ┆ from its     │
│            ┆         ┆               ┆ Jihadi       ┆ Afghanistan  ┆              ┆ relevance to │
│            ┆         ┆               ┆ society,     ┆ wars, the $8 ┆              ┆ the core     │
│            ┆         ┆               ┆ who's goal   ┆ trillion war ┆              ┆ conflict     │
│            ┆         ┆               ┆ is the exter ┆ on terror    ┆              ┆ itself.      │
│            ┆         ┆               ┆ mination of  ┆ (equal to 20 ┆              ┆              │
│            ┆         ┆               ┆ their        ┆ million      ┆              ┆              │
│            ┆         ┆               ┆ neighbors,   ┆ homes in     ┆              ┆              │
│            ┆         ┆               ┆ who refused  ┆ wealth), and ┆              ┆              │
│            ┆         ┆               ┆ multiple 2   ┆ the 9/11     ┆              ┆              │
│            ┆         ┆               ┆ state        ┆ attacks.     ┆              ┆              │
│            ┆         ┆               ┆ solutions,   ┆ Take action, ┆              ┆              │
│            ┆         ┆               ┆ and even     ┆ and boycott  ┆              ┆              │
│            ┆         ┆               ┆ they         ┆ Israel. Deta ┆              ┆              │
│            ┆         ┆               ┆ themselves   ┆ ils [here](h ┆              ┆              │
│            ┆         ┆               ┆ don't want a ┆ ttps://drive ┆              ┆              │
│            ┆         ┆               ┆ country      ┆ .proton.me/u ┆              ┆              │
│            ┆         ┆               ┆ unless it is ┆ rls/YN52AE6Y ┆              ┆              │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 3

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ murbg5q    ┆ 1kxjjli ┆ Black         ┆ [https://x.c ┆ Yeah, it is  ┆ 3            ┆ The comment  │
│            ┆         ┆ Americans go  ┆ om/LaCienega ┆ a MAJOR      ┆              ┆ discusses    │
│            ┆         ┆ to Palestine  ┆ Blvdss/statu ┆ problem in   ┆              ┆ racism in    │
│            ┆         ┆ to support    ┆ s/1913985212 ┆ the Middle   ┆              ┆ the Middle   │
│            ┆         ┆ and face      ┆ 410740972?re ┆ East. Not    ┆              ┆ East,        │
│            ┆         ┆ racism from   ┆ f\_src=twsrc ┆ only in the  ┆              ┆ particularly │
│            ┆         ┆ the           ┆ %5Etfw%7Ctwc ┆ Palestinian  ┆              ┆ in relation  │
│            ┆         ┆ Palestinians  ┆ amp%5Etweete ┆ areas, but   ┆              ┆ to           │
│            ┆         ┆ (word is they ┆ mbed%7Ctwter ┆ also in many ┆              ┆ Palestinians │
│            ┆         ┆ were called   ┆ m%5E19139852 ┆ other        ┆              ┆ and their    │
│            ┆         ┆ racial slurs  ┆ 12410740972% ┆ countries in ┆              ┆ treatment of │
│            ┆         ┆ too)          ┆ 7Ctwgr%5E%7C ┆ the area,    ┆              ┆ Black        │
│            ┆         ┆               ┆ twcon%5Es1\_ ┆ that simply  ┆              ┆ Americans,   │
│            ┆         ┆               ┆ &ref\_url=]( ┆ hate         ┆              ┆ which        │
│            ┆         ┆               ┆ https://x.co ┆ Africans.    ┆              ┆ indirectly   │
│            ┆         ┆               ┆ m/LaCienegaB ┆ The Houthi   ┆              ┆ touches on   │
│            ┆         ┆               ┆ lvdss/status ┆ rebels, who  ┆              ┆ the broader  │
│            ┆         ┆               ┆ /19139852124 ┆ the pro-Pale ┆              ┆ context of   │
│            ┆         ┆               ┆ 10740972?ref ┆ stinians     ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ _src=twsrc%5 ┆ LOOVE so     ┆              ┆ conflict and │
│            ┆         ┆               ┆ Etfw%7Ctwcam ┆ much,        ┆              ┆ public       │
│            ┆         ┆               ┆ p%5Etweetemb ┆ reintroduced ┆              ┆ opinion.     │
│            ┆         ┆               ┆ ed%7Ctwterm% ┆ slavery... I ┆              ┆ However, it  │
│            ┆         ┆               ┆ 5E1913985212 ┆ haven't seen ┆              ┆ primarily    │
│            ┆         ┆               ┆ 410740972%7C ┆ ONE, not ONE ┆              ┆ focuses on   │
│            ┆         ┆               ┆ twgr%5E%7Ctw ┆ of these org ┆              ┆ racial       │
│            ┆         ┆               ┆ con%5Es1_&re ┆ anizations   ┆              ┆ issues       │
│            ┆         ┆               ┆ f_url=)      ┆ say anything ┆              ┆ rather than  │
│            ┆         ┆               ┆              ┆ bad about    ┆              ┆ the core     │
│            ┆         ┆               ┆ [https://www ┆ that...      ┆              ┆ conflict     │
│            ┆         ┆               ┆ .tiktok.com/ ┆              ┆              ┆ itself.      │
│            ┆         ┆               ┆ @hebatalks/v ┆ And you      ┆              ┆              │
│            ┆         ┆               ┆ ideo/7489954 ┆ probably     ┆              ┆              │
│            ┆         ┆               ┆ 350727433502 ┆ remember the ┆              ┆              │
│            ┆         ┆               ┆ ?\_r=1&\_t=Z ┆ famous late  ┆              ┆              │
│            ┆         ┆               ┆ P-8vhOaDP5gZ ┆ Eldridge     ┆              ┆              │
│            ┆         ┆               ┆ q](https://w ┆ Cleaver, the ┆              ┆              │
│            ┆         ┆               ┆ ww.tiktok.co ┆ minister of  ┆              ┆              │
│            ┆         ┆               ┆ m/@hebatalks ┆ information  ┆              ┆              │
│            ┆         ┆               ┆ /video/74899 ┆ for the      ┆              ┆              │
│            ┆         ┆               ┆ 543507274335 ┆ Black        ┆              ┆              │
│            ┆         ┆               ┆ 02?_r=1&_t=Z ┆ Panther      ┆              ┆              │
│            ┆         ┆               ┆ P-8vhOaDP5gZ ┆ Party and    ┆              ┆              │
│            ┆         ┆               ┆ q)           ┆ what he said ┆              ┆              │
│            ┆         ┆               ┆              ┆ about        ┆              ┆              │
│            ┆         ┆               ┆ I can't even ┆ Algeria...   ┆              ┆              │
│            ┆         ┆               ┆ listen to    ┆ He couldn't  ┆              ┆              │
│            ┆         ┆               ┆ that         ┆ believe the  ┆              ┆              │
│            ┆         ┆               ┆ Palestinian  ┆ level of     ┆              ┆              │
│            ┆         ┆               ┆ woman speak  ┆ racism he    ┆              ┆              │
│            ┆         ┆               ┆ her justific ┆ saw in       ┆              ┆              │
│            ┆         ┆               ┆ ation on all ┆ Algeria and  ┆              ┆              │
│            ┆         ┆               ┆ this.. it's  ┆ he talked    ┆              ┆              │
│            ┆         ┆               ┆ extremely    ┆ about how    ┆              ┆              │
│            ┆         ┆               ┆ cringe.      ┆ the          ┆              ┆              │
│            ┆         ┆               ┆              ┆ Algerians    ┆              ┆              │
│            ┆         ┆               ┆ She has      ┆ literally    ┆              ┆              │
│            ┆         ┆               ┆ quite a bit  ┆ had African  ┆              ┆              │
│            ┆         ┆               ┆ to say about ┆ slaves.      ┆              ┆              │
│            ┆         ┆               ┆ "You can't   ┆ After that   ┆              ┆              │
│            ┆         ┆               ┆ assume the   ┆ he became a  ┆              ┆              │
│            ┆         ┆               ┆ Palestinians ┆ Zionist and  ┆              ┆              │
│            ┆         ┆               ┆ were being   ┆ fierce       ┆              ┆              │
│            ┆         ┆               ┆ racist to    ┆ defender of  ┆              ┆              │
│            ┆         ┆               ┆ you about    ┆ Israel... He ┆              ┆              │
│            ┆         ┆               ┆ such and     ┆ made many    ┆              ┆              │
│            ┆         ┆               ┆ such issue"  ┆ controversia ┆              ┆              │
│            ┆         ┆               ┆ when she     ┆ l anti-Arab  ┆              ┆              │
│            ┆         ┆               ┆ herself      ┆ remarks, for ┆              ┆              │
│            ┆         ┆               ┆ makes so     ┆ example he   ┆              ┆              │
│            ┆         ┆               ┆ many         ┆ called Arabs ┆              ┆              │
│            ┆         ┆               ┆ assumptions  ┆ the "most    ┆              ┆              │
│            ┆         ┆               ┆ in her       ┆ racist       ┆              ┆              │
│            ┆         ┆               ┆ almost       ┆ people on    ┆              ┆              │
│            ┆         ┆               ┆ 10-minute    ┆ Earth..."    ┆              ┆              │
│            ┆         ┆               ┆ long rant.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ The          ┆              ┆              ┆              │
│            ┆         ┆               ┆ hypocrisy is ┆              ┆              ┆              │
│            ┆         ┆               ┆ abundant     ┆              ┆              ┆              │
│            ┆         ┆               ┆ here. Not to ┆              ┆              ┆              │
│            ┆         ┆               ┆ mention, if  ┆              ┆              ┆              │
│            ┆         ┆               ┆ these black  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Americans    ┆              ┆              ┆              │
│            ┆         ┆               ┆ faced so     ┆              ┆              ┆              │
│            ┆         ┆               ┆ much racism  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the whole    ┆              ┆              ┆              │
│            ┆         ┆               ┆ time, it's   ┆              ┆              ┆              │
│            ┆         ┆               ┆ becomes very ┆              ┆              ┆              │
│            ┆         ┆               ┆ clear that   ┆              ┆              ┆              │
│            ┆         ┆               ┆ they are     ┆              ┆              ┆              │
│            ┆         ┆               ┆ indeed being ┆              ┆              ┆              │
│            ┆         ┆               ┆ treated with ┆              ┆              ┆              │
│            ┆         ┆               ┆ racism when  ┆              ┆              ┆              │
│            ┆         ┆               ┆ fur…         ┆              ┆              ┆              │
│ nwxt7np    ┆ 1pwh9pg ┆ We Hung On By ┆ Devastated   ┆ This is      ┆ 3            ┆ The comment  │
│            ┆         ┆ a Thread for  ┆ right now. I ┆ literally    ┆              ┆ touches on   │
│            ┆         ┆ Two Years,    ┆ have a       ┆ insane. I’m  ┆              ┆ the          │
│            ┆         ┆ Now           ┆ friend who   ┆ so sorry. I  ┆              ┆ treatment of │
│            ┆         ┆ Friendship Is ┆ has always   ┆ feel I have  ┆              ┆ Jewish       │
│            ┆         ┆ Over          ┆ been really  ┆ gotten this  ┆              ┆ individuals  │
│            ┆         ┆               ┆ important to ┆ same         ┆              ┆ in           │
│            ┆         ┆               ┆ me. We've    ┆ treatment    ┆              ┆ discussions  │
│            ┆         ┆               ┆ been friends ┆ too. How     ┆              ┆ about the    │
│            ┆         ┆               ┆ for a        ┆ dare we care ┆              ┆ Gaza         │
│            ┆         ┆               ┆ quarter      ┆ about Jewish ┆              ┆ conflict,    │
│            ┆         ┆               ┆ century. We  ┆ people. It’s ┆              ┆ reflecting   │
│            ┆         ┆               ┆ are both     ┆ like you’re  ┆              ┆ on societal  │
│            ┆         ┆               ┆ half Jewish  ┆ a person of  ┆              ┆ standards    │
│            ┆         ┆               ┆ and have     ┆ European     ┆              ┆ and          │
│            ┆         ┆               ┆ always had   ┆ diaspora who ┆              ┆ perceptions, │
│            ┆         ┆               ┆ that         ┆ has          ┆              ┆ which        │
│            ┆         ┆               ┆ identity in  ┆ ancestors    ┆              ┆ relates to   │
│            ┆         ┆               ┆ common. He   ┆ who did      ┆              ┆ public       │
│            ┆         ┆               ┆ is super     ┆ horrific     ┆              ┆ opinion on   │
│            ┆         ┆               ┆ lefty and    ┆ things but   ┆              ┆ the          │
│            ┆         ┆               ┆ has always   ┆ somehow you  ┆              ┆ conflict.    │
│            ┆         ┆               ┆ been         ┆ get a        ┆              ┆ However, it  │
│            ┆         ┆               ┆ anti-Zionist ┆ statute of   ┆              ┆ does not     │
│            ┆         ┆               ┆ but not      ┆ limitations  ┆              ┆ directly     │
│            ┆         ┆               ┆ obsessively. ┆ for that. If ┆              ┆ address the  │
│            ┆         ┆               ┆ Not until    ┆ you are      ┆              ┆ core events  │
│            ┆         ┆               ┆ two years    ┆ Jewish you   ┆              ┆ or           │
│            ┆         ┆               ┆ ago.         ┆ are held to  ┆              ┆ humanitarian │
│            ┆         ┆               ┆              ┆ another      ┆              ┆ issues in    │
│            ┆         ┆               ┆ He started   ┆ standard and ┆              ┆ Gaza.        │
│            ┆         ┆               ┆ going cold   ┆ there are    ┆              ┆              │
│            ┆         ┆               ┆ on me when I ┆ tons of      ┆              ┆              │
│            ┆         ┆               ┆ tried to     ┆ different    ┆              ┆              │
│            ┆         ┆               ┆ talk to him  ┆ spaces that  ┆              ┆              │
│            ┆         ┆               ┆ about an     ┆ the justice  ┆              ┆              │
│            ┆         ┆               ┆ antisemitic  ┆ isn’t held   ┆              ┆              │
│            ┆         ┆               ┆ incident     ┆              ┆              ┆              │
│            ┆         ┆               ┆ that         ┆              ┆              ┆              │
│            ┆         ┆               ┆ happened at  ┆              ┆              ┆              │
│            ┆         ┆               ┆ his alma     ┆              ┆              ┆              │
│            ┆         ┆               ┆ mater. Since ┆              ┆              ┆              │
│            ┆         ┆               ┆ then we have ┆              ┆              ┆              │
│            ┆         ┆               ┆ remained     ┆              ┆              ┆              │
│            ┆         ┆               ┆ friends on   ┆              ┆              ┆              │
│            ┆         ┆               ┆ social media ┆              ┆              ┆              │
│            ┆         ┆               ┆ and I reach  ┆              ┆              ┆              │
│            ┆         ┆               ┆ out to him   ┆              ┆              ┆              │
│            ┆         ┆               ┆ at Christmas ┆              ┆              ┆              │
│            ┆         ┆               ┆ and get a    ┆              ┆              ┆              │
│            ┆         ┆               ┆ perfunctory  ┆              ┆              ┆              │
│            ┆         ┆               ┆ response.    ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ This time I  ┆              ┆              ┆              │
│            ┆         ┆               ┆ asked him    ┆              ┆              ┆              │
│            ┆         ┆               ┆ whether he   ┆              ┆              ┆              │
│            ┆         ┆               ┆ wants to     ┆              ┆              ┆              │
│            ┆         ┆               ┆ salvage the  ┆              ┆              ┆              │
│            ┆         ┆               ┆ friendship.  ┆              ┆              ┆              │
│            ┆         ┆               ┆ He told me   ┆              ┆              ┆              │
│            ┆         ┆               ┆ that he      ┆              ┆              ┆              │
│            ┆         ┆               ┆ thinks Gaza  ┆              ┆              ┆              │
│            ┆         ┆               ┆ is the       ┆              ┆              ┆              │
│            ┆         ┆               ┆ holocaust of ┆              ┆              ┆              │
│            ┆         ┆               ┆ our time and ┆              ┆              ┆              │
│            ┆         ┆               ┆ he is afraid ┆              ┆              ┆              │
│            ┆         ┆               ┆ to know what ┆              ┆              ┆              │
│            ┆         ┆               ┆ my views     ┆              ┆              ┆              │
│            ┆         ┆               ┆ are. That's  ┆              ┆              ┆              │
│            ┆         ┆               ┆ why he       ┆              ┆              ┆              │
│            ┆         ┆               ┆ hasn't       ┆              ┆              ┆              │
│            ┆         ┆               ┆ talked to    ┆              ┆              ┆              │
│            ┆         ┆               ┆ me.          ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Basically he ┆              ┆              ┆              │
│            ┆         ┆               ┆ was          ┆              ┆              ┆              │
│            ┆         ┆               ┆ performing   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the purity   ┆              ┆              ┆              │
│            ┆         ┆               ┆ test on me.  ┆              ┆              ┆              │
│            ┆         ┆               ┆ So I told    ┆              ┆              ┆              │
│            ┆         ┆               ┆ him my views ┆              ┆              ┆              │
│            ┆         ┆               ┆ and reminded ┆              ┆              ┆              │
│            ┆         ┆               ┆ him of the   ┆              ┆              ┆              │
│            ┆         ┆               ┆ way I stood  ┆              ┆              ┆              │
│            ┆         ┆               ┆ up for Musli ┆              ┆              ┆              │
│            ┆         ┆               ┆ ms/Arabs who ┆              ┆              ┆              │
│            ┆         ┆               ┆ were being   ┆              ┆              ┆              │
│            ┆         ┆               ┆ harassed and ┆              ┆              ┆              │
│            ┆         ┆               ┆ threatened   ┆              ┆              ┆              │
│            ┆         ┆               ┆ after 9/11.  ┆              ┆              ┆              │
│            ┆         ┆               ┆ (I literally ┆              ┆              ┆              │
│            ┆         ┆               ┆ stood up and ┆              ┆              ┆              │
│            ┆         ┆               ┆ faced a      ┆              ┆              ┆              │
│            ┆         ┆               ┆ couple of    ┆              ┆              ┆              │
│            ┆         ┆               ┆ thugs who    ┆              ┆              ┆              │
│            ┆         ┆               ┆ were         ┆              ┆              ┆              │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 4

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ n9w97kn    ┆ 1mwbg7i ┆ Netanyahu:    ┆ Welp, i      ┆ It only took ┆ 4            ┆ The comment  │
│            ┆         ┆ Israel will   ┆ guess the    ┆ them 2 years ┆              ┆ expresses    │
│            ┆         ┆ conquer Gaza  ┆ decision is  ┆ to do        ┆              ┆ skepticism   │
│            ┆         ┆ regardless of ┆ made         ┆ something    ┆              ┆ about        │
│            ┆         ┆ whether Hamas ┆ then.....    ┆ that should  ┆              ┆ Israel's     │
│            ┆         ┆ accepts       ┆              ┆ have been    ┆              ┆ actions      │
│            ┆         ┆ hostage deal  ┆              ┆ done since   ┆              ┆ regarding    │
│            ┆         ┆               ┆              ┆ day 1 🙄     ┆              ┆ Gaza,        │
│            ┆         ┆               ┆              ┆              ┆              ┆ indicating a │
│            ┆         ┆               ┆              ┆ Now let's    ┆              ┆ direct       │
│            ┆         ┆               ┆              ┆ see if       ┆              ┆ engagement   │
│            ┆         ┆               ┆              ┆ they'll      ┆              ┆ with the     │
│            ┆         ┆               ┆              ┆ actually     ┆              ┆ ongoing      │
│            ┆         ┆               ┆              ┆ follow       ┆              ┆ conflict and │
│            ┆         ┆               ┆              ┆ through      ┆              ┆ its implicat │
│            ┆         ┆               ┆              ┆ instead of   ┆              ┆ ions, which  │
│            ┆         ┆               ┆              ┆ just talking ┆              ┆ aligns with  │
│            ┆         ┆               ┆              ┆              ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆              ┆              ┆ issues at    │
│            ┆         ┆               ┆              ┆              ┆              ┆ hand.        │
│ mq0qal3    ┆ 1kbq23d ┆ best way for  ┆ hello        ┆ thank you so ┆ 4            ┆ The comment  │
│            ┆         ┆ american to   ┆ everyone.    ┆ much for     ┆              ┆ provides a   │
│            ┆         ┆ get money to  ┆ myself and a ┆ doing this,  ┆              ┆ suggestion   │
│            ┆         ┆ a gaza        ┆ group of     ┆ you can send ┆              ┆ for sending  │
│            ┆         ┆ refugee?      ┆ people are   ┆ it direct to ┆              ┆ money        │
│            ┆         ┆               ┆ trying to    ┆ Bank of      ┆              ┆ directly to  │
│            ┆         ┆               ┆ send the     ┆ Palestine in ┆              ┆ the Bank of  │
│            ┆         ┆               ┆ donations we ┆ case they    ┆              ┆ Palestine,   │
│            ┆         ┆               ┆ have         ┆ have a bank  ┆              ┆ which is     │
│            ┆         ┆               ┆ accumulated  ┆ account.     ┆              ┆ relevant to  │
│            ┆         ┆               ┆ to a family  ┆ also please  ┆              ┆ the          │
│            ┆         ┆               ┆ in gaza, but ┆ check your   ┆              ┆ humanitarian │
│            ┆         ┆               ┆ we are       ┆ DM!          ┆              ┆ efforts      │
│            ┆         ┆               ┆ running into ┆              ┆              ┆ related to   │
│            ┆         ┆               ┆ several      ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ problems.    ┆              ┆              ┆ conflict. It │
│            ┆         ┆               ┆              ┆              ┆              ┆ addresses    │
│            ┆         ┆               ┆ The money    ┆              ┆              ┆ the          │
│            ┆         ┆               ┆ from the     ┆              ┆              ┆ logistical   │
│            ┆         ┆               ┆ gofundme is  ┆              ┆              ┆ challenges   │
│            ┆         ┆               ┆ saved in a   ┆              ┆              ┆ of           │
│            ┆         ┆               ┆ separate     ┆              ┆              ┆ supporting   │
│            ┆         ┆               ┆ bank account ┆              ┆              ┆ individuals  │
│            ┆         ┆               ┆ specifically ┆              ┆              ┆ in Gaza,     │
│            ┆         ┆               ┆ for Amal,    ┆              ┆              ┆ making it    │
│            ┆         ┆               ┆ that way it  ┆              ┆              ┆ clearly      │
│            ┆         ┆               ┆ never gets   ┆              ┆              ┆ related to   │
│            ┆         ┆               ┆ mixed up.    ┆              ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆              ┆              ┆ issues at    │
│            ┆         ┆               ┆ We usually   ┆              ┆              ┆ hand.        │
│            ┆         ┆               ┆ wire the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ money        ┆              ┆              ┆              │
│            ┆         ┆               ┆ through      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Western      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Union, and   ┆              ┆              ┆              │
│            ┆         ┆               ┆ cash pick up ┆              ┆              ┆              │
│            ┆         ┆               ┆ is the only  ┆              ┆              ┆              │
│            ┆         ┆               ┆ option       ┆              ┆              ┆              │
│            ┆         ┆               ┆ available.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ While that   ┆              ┆              ┆              │
│            ┆         ┆               ┆ had its      ┆              ┆              ┆              │
│            ┆         ┆               ┆ drawbacks    ┆              ┆              ┆              │
│            ┆         ┆               ┆ (huge        ┆              ┆              ┆              │
│            ┆         ┆               ┆ "service"    ┆              ┆              ┆              │
│            ┆         ┆               ┆ costs and a  ┆              ┆              ┆              │
│            ┆         ┆               ┆ cap from     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israhell     ┆              ┆              ┆              │
│            ┆         ┆               ┆ allowing     ┆              ┆              ┆              │
│            ┆         ┆               ┆ only 7500 to ┆              ┆              ┆              │
│            ┆         ┆               ┆ be sent to   ┆              ┆              ┆              │
│            ┆         ┆               ┆ one person   ┆              ┆              ┆              │
│            ┆         ┆               ┆ in Palestine ┆              ┆              ┆              │
│            ┆         ┆               ┆ per month,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ along with   ┆              ┆              ┆              │
│            ┆         ┆               ┆ it only      ┆              ┆              ┆              │
│            ┆         ┆               ┆ being open   ┆              ┆              ┆              │
│            ┆         ┆               ┆ once a week) ┆              ┆              ┆              │
│            ┆         ┆               ┆ it DID work. ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ That office  ┆              ┆              ┆              │
│            ┆         ┆               ┆ that Amal    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and          ┆              ┆              ┆              │
│            ┆         ┆               ┆ Awadallah    ┆              ┆              ┆              │
│            ┆         ┆               ┆ had to       ┆              ┆              ┆              │
│            ┆         ┆               ┆ physically   ┆              ┆              ┆              │
│            ┆         ┆               ┆ travel to,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ which is     ┆              ┆              ┆              │
│            ┆         ┆               ┆ incredibly   ┆              ┆              ┆              │
│            ┆         ┆               ┆ dangerous,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ is now...clo ┆              ┆              ┆              │
│            ┆         ┆               ┆ sed. For     ┆              ┆              ┆              │
│            ┆         ┆               ┆ obvious      ┆              ┆              ┆              │
│            ┆         ┆               ┆ reasons.     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ They can no  ┆              ┆              ┆              │
│            ┆         ┆               ┆ longer       ┆              ┆              ┆              │
│            ┆         ┆               ┆ access the   ┆              ┆              ┆              │
│            ┆         ┆               ┆ money        ┆              ┆              ┆              │
│            ┆         ┆               ┆ through      ┆              ┆              ┆              │
│            ┆         ┆               ┆ those means. ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ The US does  ┆              ┆              ┆              │
│            ┆         ┆               ┆ not allow    ┆              ┆              ┆              │
│            ┆         ┆               ┆ for a direct ┆              ┆              ┆              │
│            ┆         ┆               ┆ send to the  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Bank of      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Palestine as ┆              ┆              ┆              │
│            ┆         ┆               ┆ it is a      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Zionist      ┆              ┆              ┆              │
│            ┆         ┆               ┆ country.     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Many         ┆              ┆              ┆              │
│            ┆         ┆               ┆ countries in ┆              ┆              ┆              │
│            ┆         ┆               ┆ Europe are   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the same,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ though there ┆              ┆              ┆              │
│            ┆         ┆               ┆ are some     ┆              ┆              ┆              │
│            ┆         ┆               ┆ that do like ┆              ┆              ┆              │
│            ┆         ┆               ┆ the          ┆              ┆              ┆              │
│            ┆         ┆               ┆ Netherlands. ┆              ┆              ┆              │
│            ┆         ┆               ┆ So no direct ┆              ┆              ┆              │
│            ┆         ┆               ┆ bank         ┆              ┆              ┆              │
│            ┆         ┆               ┆ transfers.   ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ If there…    ┆              ┆              ┆              │
│ ng8etbm    ┆ 1nqbc6v ┆ Flotilla =    ┆ The Israeli  ┆ Anyone who   ┆ 4            ┆ The comment  │
│            ┆         ┆ Hamas         ┆ government   ┆ rejects      ┆              ┆ critiques    │
│            ┆         ┆               ┆ is holding a ┆ their        ┆              ┆ Israel's     │
│            ┆         ┆               ┆ press        ┆ proposal is  ┆              ┆ perception   │
│            ┆         ┆               ┆ conference   ┆ Hamas in     ┆              ┆ of those who │
│            ┆         ┆               ┆ right now    ┆ their eyes.  ┆              ┆ oppose its   │
│            ┆         ┆               ┆ calling the  ┆ I suspect    ┆              ┆ actions and  │
│            ┆         ┆               ┆ Flotilla     ┆ that it is a ┆              ┆ discusses    │
│            ┆         ┆               ┆ Hamas. I     ┆ projection   ┆              ┆ the          │
│            ┆         ┆               ┆ hope the     ┆ because      ┆              ┆ humanitarian │
│            ┆         ┆               ┆ Spanish and  ┆ Israel buys, ┆              ┆ aspect of    │
│            ┆         ┆               ┆ Italian      ┆ guilts, or   ┆              ┆ the          │
│            ┆         ┆               ┆ naval ships  ┆ backmails    ┆              ┆ conflict,    │
│            ┆         ┆               ┆ get there    ┆ anyone who   ┆              ┆ which        │
│            ┆         ┆               ┆ quickly.     ┆ still        ┆              ┆ relates      │
│            ┆         ┆               ┆              ┆ supports     ┆              ┆ directly to  │
│            ┆         ┆               ┆              ┆ Israel at    ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆ this stage.  ┆              ┆ issues       │
│            ┆         ┆               ┆              ┆ Israel       ┆              ┆ surrounding  │
│            ┆         ┆               ┆              ┆ simply can't ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆ understand a ┆              ┆ conflict.    │
│            ┆         ┆               ┆              ┆ group of     ┆              ┆              │
│            ┆         ┆               ┆              ┆ people       ┆              ┆              │
│            ┆         ┆               ┆              ┆ coming to    ┆              ┆              │
│            ┆         ┆               ┆              ┆ the aid of   ┆              ┆              │
│            ┆         ┆               ┆              ┆ people and   ┆              ┆              │
│            ┆         ┆               ┆              ┆ bringing     ┆              ┆              │
│            ┆         ┆               ┆              ┆ attention to ┆              ┆              │
│            ┆         ┆               ┆              ┆ a genocide   ┆              ┆              │
│            ┆         ┆               ┆              ┆ without      ┆              ┆              │
│            ┆         ┆               ┆              ┆ ulterior     ┆              ┆              │
│            ┆         ┆               ┆              ┆ motives.     ┆              ┆              │
│ noglo8h    ┆ 1ov0tur ┆ Why Even      ┆ It’s been    ┆ Support for  ┆ 4            ┆ The comment  │
│            ┆         ┆ Critical Jews ┆ hard lately  ┆ Israel is    ┆              ┆ addresses    │
│            ┆         ┆ Still Support ┆ to be a Jew  ┆ decreasing   ┆              ┆ the decline  │
│            ┆         ┆ Israel        ┆ or Israeli   ┆ by the       ┆              ┆ in support   │
│            ┆         ┆               ┆ and watch    ┆ minute       ┆              ┆ for Israel   │
│            ┆         ┆               ┆ what’s       ┆ despite      ┆              ┆ and          │
│            ┆         ┆               ┆ happening in ┆ being on the ┆              ┆ critiques    │
│            ┆         ┆               ┆ Gaza: the    ┆ right side   ┆              ┆ the public   │
│            ┆         ┆               ┆ destruction, ┆ of history   ┆              ┆ relations    │
│            ┆         ┆               ┆ the deaths,  ┆ for the      ┆              ┆ efforts      │
│            ┆         ┆               ┆ the          ┆ better part  ┆              ┆ surrounding  │
│            ┆         ┆               ┆ unbearable   ┆ of several   ┆              ┆ the          │
│            ┆         ┆               ┆ images. You  ┆ decades      ┆              ┆ conflict,    │
│            ┆         ┆               ┆ can’t ignore ┆              ┆              ┆ which are    │
│            ┆         ┆               ┆ it, and you  ┆ The reason   ┆              ┆ directly     │
│            ┆         ┆               ┆ shouldn’t.   ┆ is because   ┆              ┆ related to   │
│            ┆         ┆               ┆ It makes you ┆ of an        ┆              ┆ public       │
│            ┆         ┆               ┆ question     ┆ atrocious PR ┆              ┆ opinion on   │
│            ┆         ┆               ┆ everything:  ┆ campaign and ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ your         ┆ the same     ┆              ┆ conflict and │
│            ┆         ┆               ┆ country,     ┆ tired logic  ┆              ┆ its          │
│            ┆         ┆               ┆ your values, ┆ of anti      ┆              ┆ perception   │
│            ┆         ┆               ┆ your own     ┆ semitism wea ┆              ┆ in the       │
│            ┆         ┆               ┆ sense of     ┆ ponization   ┆              ┆ media.       │
│            ┆         ┆               ┆ morality.    ┆ employed by  ┆              ┆              │
│            ┆         ┆               ┆              ┆ several      ┆              ┆              │
│            ┆         ┆               ┆ If an        ┆ people on    ┆              ┆              │
│            ┆         ┆               ┆ Israeli      ┆ this sub.    ┆              ┆              │
│            ┆         ┆               ┆ really dives ┆ Absolutely   ┆              ┆              │
│            ┆         ┆               ┆ deep into    ┆ zero self    ┆              ┆              │
│            ┆         ┆               ┆ the history  ┆ awareness    ┆              ┆              │
│            ┆         ┆               ┆ and social   ┆ and lessons  ┆              ┆              │
│            ┆         ┆               ┆ dynamics     ┆ learned      ┆              ┆              │
│            ┆         ┆               ┆ that brought ┆              ┆              ┆              │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 5

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ nbek5lh    ┆ 1n33b22 ┆ Israeli Army  ┆              ┆ I have a     ┆ 5            ┆ The comment  │
│            ┆         ┆ Recovers Body ┆              ┆ feeling soon ┆              ┆ expresses    │
│            ┆         ┆ of Ilan       ┆              ┆ the rest of  ┆              ┆ concern      │
│            ┆         ┆ Weiss,        ┆              ┆ the hostages ┆              ┆ about the    │
│            ┆         ┆ Kidnapped to  ┆              ┆ will be      ┆              ┆ fate of      │
│            ┆         ┆ Gaza on       ┆              ┆ found, dont  ┆              ┆ hostages     │
│            ┆         ┆ October 7     ┆              ┆ know if      ┆              ┆ taken to     │
│            ┆         ┆               ┆              ┆ anymore will ┆              ┆ Gaza, which  │
│            ┆         ┆               ┆              ┆ be alive but ┆              ┆ is directly  │
│            ┆         ┆               ┆              ┆ we can pray  ┆              ┆ related to   │
│            ┆         ┆               ┆              ┆ that some    ┆              ┆ the ongoing  │
│            ┆         ┆               ┆              ┆ will make it ┆              ┆ conflict and │
│            ┆         ┆               ┆              ┆ out alive    ┆              ┆ its          │
│            ┆         ┆               ┆              ┆              ┆              ┆ humanitarian │
│            ┆         ┆               ┆              ┆              ┆              ┆ implications │
│            ┆         ┆               ┆              ┆              ┆              ┆ .            │
│ mpk6msk    ┆ 1ka46zf ┆ I'm so        ┆ I followed a ┆ They most    ┆ 5            ┆ The comment  │
│            ┆         ┆ fucking angry ┆ link from    ┆ certainly    ┆              ┆ directly     │
│            ┆         ┆               ┆ another post ┆ DID say      ┆              ┆ addresses    │
│            ┆         ┆               ┆ on this sub  ┆ "death to    ┆              ┆ the chanting │
│            ┆         ┆               ┆ to read a    ┆ Arabs".      ┆              ┆ of anti-Arab │
│            ┆         ┆               ┆ couple       ┆ "Ma'avet     ┆              ┆ slogans and  │
│            ┆         ┆               ┆ articles on  ┆ La'aravim"   ┆              ┆ the          │
│            ┆         ┆               ┆ a zionist    ┆ is death to  ┆              ┆ implications │
│            ┆         ┆               ┆ groups'      ┆ Arabs, and   ┆              ┆ of Zionism,  │
│            ┆         ┆               ┆ assault on   ┆ this Zionist ┆              ┆ which are    │
│            ┆         ┆               ┆ an           ┆ was trying   ┆              ┆ relevant to  │
│            ┆         ┆               ┆ antizionist  ┆ to gaslight  ┆              ┆ the ongoing  │
│            ┆         ┆               ┆ Jew in NYC,  ┆ me into      ┆              ┆ conflict and │
│            ┆         ┆               ┆ along with a ┆ believing    ┆              ┆ public       │
│            ┆         ┆               ┆ video of     ┆ they were    ┆              ┆ sentiment    │
│            ┆         ┆               ┆ zionists     ┆ chanting     ┆              ┆ surrounding  │
│            ┆         ┆               ┆ chanting     ┆ "truth for   ┆              ┆ it. This     │
│            ┆         ┆               ┆ "death to    ┆ the Jews"    ┆              ┆ discussion   │
│            ┆         ┆               ┆ arabs" and   ┆ which is     ┆              ┆ of specific  │
│            ┆         ┆               ┆ "fuck fuck   ┆ "Emet        ┆              ┆ incidents    │
│            ┆         ┆               ┆ palestine"   ┆ La'yehudim". ┆              ┆ and their    │
│            ┆         ┆               ┆ (I admit     ┆ I don't know ┆              ┆ broader      │
│            ┆         ┆               ┆ that I       ┆ how that's   ┆              ┆ societal     │
│            ┆         ┆               ┆ couldn't     ┆ even an      ┆              ┆ impact ties  │
│            ┆         ┆               ┆ tell what    ┆ argument     ┆              ┆ closely to   │
│            ┆         ┆               ┆ they were    ┆ floating     ┆              ┆ the core     │
│            ┆         ┆               ┆ saying from  ┆ around, the  ┆              ┆ issues of    │
│            ┆         ┆               ┆ the audio    ┆ two aren't   ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ but that is  ┆ easy to      ┆              ┆ conflict.    │
│            ┆         ┆               ┆ what the     ┆ confuse even ┆              ┆              │
│            ┆         ┆               ┆ captions     ┆ for          ┆              ┆              │
│            ┆         ┆               ┆ said. I      ┆ non-Hebrew   ┆              ┆              │
│            ┆         ┆               ┆ guess it's   ┆ speakers     ┆              ┆              │
│            ┆         ┆               ┆ possible the ┆              ┆              ┆              │
│            ┆         ┆               ┆ captions     ┆              ┆              ┆              │
│            ┆         ┆               ┆ could be     ┆              ┆              ┆              │
│            ┆         ┆               ┆ inaccurate   ┆              ┆              ┆              │
│            ┆         ┆               ┆ but I'm not  ┆              ┆              ┆              │
│            ┆         ┆               ┆ sure they    ┆              ┆              ┆              │
│            ┆         ┆               ┆ are).        ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Just fucking ┆              ┆              ┆              │
│            ┆         ┆               ┆ IMAGINE if a ┆              ┆              ┆              │
│            ┆         ┆               ┆ pro-israel   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jew was      ┆              ┆              ┆              │
│            ┆         ┆               ┆ assaulted by ┆              ┆              ┆              │
│            ┆         ┆               ┆ a crowd of   ┆              ┆              ┆              │
│            ┆         ┆               ┆ people       ┆              ┆              ┆              │
│            ┆         ┆               ┆ screaming    ┆              ┆              ┆              │
│            ┆         ┆               ┆ 'death to    ┆              ┆              ┆              │
│            ┆         ┆               ┆ jews'. Hell, ┆              ┆              ┆              │
│            ┆         ┆               ┆ I bet a      ┆              ┆              ┆              │
│            ┆         ┆               ┆ headline     ┆              ┆              ┆              │
│            ┆         ┆               ┆ like that    ┆              ┆              ┆              │
│            ┆         ┆               ┆ has already  ┆              ┆              ┆              │
│            ┆         ┆               ┆ been         ┆              ┆              ┆              │
│            ┆         ┆               ┆ fabricated   ┆              ┆              ┆              │
│            ┆         ┆               ┆ by some      ┆              ┆              ┆              │
│            ┆         ┆               ┆ zionist out  ┆              ┆              ┆              │
│            ┆         ┆               ┆ there.       ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Zionism in   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the name of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ safety is    ┆              ┆              ┆              │
│            ┆         ┆               ┆ anti-safety. ┆              ┆              ┆              │
│            ┆         ┆               ┆ For          ┆              ┆              ┆              │
│            ┆         ┆               ┆ EVERYONE.    ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ It is anti   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israeli      ┆              ┆              ┆              │
│            ┆         ┆               ┆ safety, anti ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jewish       ┆              ┆              ┆              │
│            ┆         ┆               ┆ safety, anti ┆              ┆              ┆              │
│            ┆         ┆               ┆ childrens    ┆              ┆              ┆              │
│            ┆         ┆               ┆ safety, anti ┆              ┆              ┆              │
│            ┆         ┆               ┆ journalistic ┆              ┆              ┆              │
│            ┆         ┆               ┆ safety, anti ┆              ┆              ┆              │
│            ┆         ┆               ┆ free speech. ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ I am so      ┆              ┆              ┆              │
│            ┆         ┆               ┆ fucking SICK ┆              ┆              ┆              │
│            ┆         ┆               ┆ of the lies  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and the      ┆              ┆              ┆              │
│            ┆         ┆               ┆ bullshit.    ┆              ┆              ┆              │
│            ┆         ┆               ┆ These people ┆              ┆              ┆              │
│            ┆         ┆               ┆ - many of    ┆              ┆              ┆              │
│            ┆         ┆               ┆ whom         ┆              ┆              ┆              │
│            ┆         ┆               ┆ otherwise    ┆              ┆              ┆              │
│            ┆         ┆               ┆ claim to be  ┆              ┆              ┆              │
│            ┆         ┆               ┆ lefties -    ┆              ┆              ┆              │
│            ┆         ┆               ┆ are guzzling ┆              ┆              ┆              │
│            ┆         ┆               ┆ the dick of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ fascism      ┆              ┆              ┆              │
│            ┆         ┆               ┆ because of   ┆              ┆              ┆              │
│            ┆         ┆               ┆ their        ┆              ┆              ┆              │
│            ┆         ┆               ┆ blind-ass    ┆              ┆              ┆              │
│            ┆         ┆               ┆ stance on    ┆              ┆              ┆              │
│            ┆         ┆               ┆ this one     ┆              ┆              ┆              │
│            ┆         ┆               ┆ issue. They  ┆              ┆              ┆              │
│            ┆         ┆               ┆ have         ┆              ┆              ┆              │
│            ┆         ┆               ┆ completely   ┆              ┆              ┆              │
│            ┆         ┆               ┆ lost the…    ┆              ┆              ┆              │
│ n7enm49    ┆ 1mjtc9u ┆ Tired of this ┆ Time to      ┆ This is      ┆ 5            ┆ The comment  │
│            ┆         ┆ anti-Gazan    ┆ speak out    ┆ correct      ┆              ┆ addresses    │
│            ┆         ┆ hivemind      ┆ about the    ┆ except for 2 ┆              ┆ the rhetoric │
│            ┆         ┆ rhetoric -    ┆ Anti-Gazan   ┆ things:      ┆              ┆ surrounding  │
│            ┆         ┆ all people    ┆ rhetoric and ┆              ┆              ┆ Gazans and   │
│            ┆         ┆ are           ┆ continue to  ┆ \- Hamas     ┆              ┆ collective   │
│            ┆         ┆ individuals!  ┆ remind       ┆ since being  ┆              ┆ punishment,  │
│            ┆         ┆               ┆ people that  ┆ elected in   ┆              ┆ discussing   │
│            ┆         ┆               ┆ there are    ┆ 2006 is the  ┆              ┆ the          │
│            ┆         ┆               ┆ all types of ┆ political    ┆              ┆ implications │
│            ┆         ┆               ┆ people in    ┆ party that   ┆              ┆ of such      │
│            ┆         ┆               ┆ Gaza!!! Yes, ┆ hasn't       ┆              ┆ views on     │
│            ┆         ┆               ┆ humans       ┆ changed in   ┆              ┆ public       │
│            ┆         ┆               ┆ actually     ┆ 19 years.    ┆              ┆ perception   │
│            ┆         ┆               ┆ have         ┆              ┆              ┆ and internat │
│            ┆         ┆               ┆ **nuance**   ┆ \- Israeli   ┆              ┆ ional law,   │
│            ┆         ┆               ┆ and **indivi ┆ Prime        ┆              ┆ which are    │
│            ┆         ┆               ┆ duality**,   ┆ Minister     ┆              ┆ directly     │
│            ┆         ┆               ┆ surprising!  ┆ Naftali      ┆              ┆ related to   │
│            ┆         ┆               ┆ Yes, sci-fi  ┆ Bennet has   ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ is very fun  ┆ indicated    ┆              ┆ conflict.    │
│            ┆         ┆               ┆ to read, but ┆ that Hamas   ┆              ┆              │
│            ┆         ┆               ┆ Gazans are   ┆ has 76/132   ┆              ┆              │
│            ┆         ┆               ┆ not capable  ┆ seats in     ┆              ┆              │
│            ┆         ┆               ┆ of hivemind  ┆ Palestine    ┆              ┆              │
│            ┆         ┆               ┆ thinking,    ┆ Parliament   ┆              ┆              │
│            ┆         ┆               ┆ just like    ┆ or over 50%, ┆              ┆              │
│            ┆         ┆               ┆ the rest of  ┆ [https://abc ┆              ┆              │
│            ┆         ┆               ┆ us humans,   ┆ news.go.com/ ┆              ┆              │
│            ┆         ┆               ┆ although     ┆ Internationa ┆              ┆              │
│            ┆         ┆               ┆ that would   ┆ l/former-isr ┆              ┆              │
│            ┆         ┆               ┆ be *really   ┆ aeli-prime-m ┆              ┆              │
│            ┆         ┆               ┆ cool!*       ┆ inister-naft ┆              ┆              │
│            ┆         ┆               ┆              ┆ ali-bennett- ┆              ┆              │
│            ┆         ┆               ┆ >**Hive      ┆ vies-positio ┆              ┆              │
│            ┆         ┆               ┆ mind:** the  ┆ n/story?id=1 ┆              ┆              │
│            ┆         ┆               ┆ collective   ┆ 13345773](ht ┆              ┆              │
│            ┆         ┆               ┆ mental       ┆ tps://abcnew ┆              ┆              │
│            ┆         ┆               ┆ activity     ┆ s.go.com/Int ┆              ┆              │
│            ┆         ┆               ┆ expressed in ┆ ernational/f ┆              ┆              │
│            ┆         ┆               ┆ the complex, ┆ ormer-israel ┆              ┆              │
│            ┆         ┆               ┆ coordinated  ┆ i-prime-mini ┆              ┆              │
│            ┆         ┆               ┆ behavior of  ┆ ster-naftali ┆              ┆              │
│            ┆         ┆               ┆ a colony of  ┆ -bennett-vie ┆              ┆              │
│            ┆         ┆               ┆ social       ┆ s-position/s ┆              ┆              │
│            ┆         ┆               ┆ insects      ┆ tory?id=1133 ┆              ┆              │
│            ┆         ┆               ┆ (such as     ┆ 45773)       ┆              ┆              │
│            ┆         ┆               ┆ bees or      ┆              ┆              ┆              │
│            ┆         ┆               ┆ ants)        ┆              ┆              ┆              │
│            ┆         ┆               ┆ regarded as  ┆              ┆              ┆              │
│            ┆         ┆               ┆ comparable   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to a single  ┆              ┆              ┆              │
│            ┆         ┆               ┆ mind         ┆              ┆              ┆              │
│            ┆         ┆               ┆ controlling  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the behavior ┆              ┆              ┆              │
│            ┆         ┆               ┆ of an        ┆              ┆              ┆              │
│            ┆         ┆               ┆ individual   ┆              ┆              ┆              │
│            ┆         ┆               ┆ organism     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ [https://www ┆              ┆              ┆              │
│            ┆         ┆               ┆ .merriam-web ┆              ┆              ┆              │
│            ┆         ┆               ┆ ster.com/dic ┆              ┆              ┆              │
│            ┆         ┆               ┆ tionary/hive ┆              ┆              ┆              │
│            ┆         ┆               ┆ %20mind](htt ┆              ┆              ┆              │
│            ┆         ┆               ┆ ps://www.mer ┆              ┆              ┆              │
│            ┆         ┆               ┆ riam-webster ┆              ┆              ┆              │
│            ┆         ┆               ┆ .com/diction ┆              ┆              ┆              │
│            ┆         ┆               ┆ ary/hive%20m ┆              ┆              ┆              │
│            ┆         ┆               ┆ ind)         ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ If you don't ┆              ┆              ┆              │
│            ┆         ┆               ┆ like being   ┆              ┆              ┆              │

========================================================================================================================================================================================================

---

In [26]:
import json
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
labeling_dir = os.path.join(project_path, 'data', 'labeled_samples')
val_sample_path = os.path.join(labeling_dir, '04a_validation_sample.json')
with open(val_sample_path, "r", encoding="utf-8") as f:
    val_sample = json.load(f)

In [28]:
comment_ids = [x['comment_id'] for x in val_sample]

In [31]:
processed_df_filtered.filter(
    pl.col('comment_id').is_in(comment_ids),
    pl.col('content_relevance_score') == 4
    )

shape: (18, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ mtwl83s    ┆ 1kt11kd ┆ Dana Bash and ┆              ┆ Hahaha I     ┆ 4            ┆ Primary      │
│            ┆         ┆ guest: “Free  ┆              ┆ caught the   ┆              ┆ subject: int │
│            ┆         ┆ Palestine”    ┆              ┆ sarcasm you  ┆              ┆ erpretation  │
│            ┆         ┆ means         ┆              ┆ actually     ┆              ┆ of the 'Free │
│            ┆         ┆ violence      ┆              ┆ mean free    ┆              ┆ Palestine'   │
│            ┆         ┆ against Jews  ┆              ┆ Palestine is ┆              ┆ slogan in    │
│            ┆         ┆               ┆              ┆ free         ┆              ┆ response to  │
│            ┆         ┆               ┆              ┆ Palestine    ┆              ┆ a media      │
│            ┆         ┆               ┆              ┆              ┆              ┆ claim; this  │
│            ┆         ┆               ┆              ┆              ┆              ┆ is a brief   │
│            ┆         ┆               ┆              ┆              ┆              ┆ reaction     │
│            ┆         ┆               ┆              ┆              ┆              ┆ about        │
│            ┆         ┆               ┆              ┆              ┆              ┆ protest      │
│            ┆         ┆               ┆              ┆              ┆              ┆ messaging    │
│            ┆         ┆               ┆              ┆              ┆              ┆ and public   │
│            ┆         ┆               ┆              ┆              ┆              ┆ opinion      │
│            ┆         ┆               ┆              ┆              ┆              ┆ related to   │
│            ┆         ┆               ┆              ┆              ┆              ┆ the Gaza/Pal │
│            ┆         ┆               ┆              ┆              ┆              ┆ estine       │
│            ┆         ┆               ┆              ┆              ┆              ┆ issue, so it │
│            ┆         ┆               ┆              ┆              ┆              ┆ fits the 'me │
│            ┆         ┆               ┆              ┆              ┆              ┆ dia/opinion/ │
│            ┆         ┆               ┆              ┆              ┆              ┆ protests'    │
│            ┆         ┆               ┆              ┆              ┆              ┆ category.    │
│ nd24kod    ┆ 1nbhq9c ┆ [MEGATHREAD]  ┆ As of 14:23  ┆ I'm not from ┆ 4            ┆ The comment  │
│            ┆         ┆ Numerous      ┆ am Israeli   ┆ Israel, but  ┆              ┆ expresses    │
│            ┆         ┆ injured and   ┆ time, there  ┆ I just came  ┆              ┆ sympathy for │
│            ┆         ┆ dead reported ┆ are reports  ┆ to say that  ┆              ┆ the victims  │
│            ┆         ┆ in major      ┆ of 6 dead    ┆ this is hear ┆              ┆ of a violent │
│            ┆         ┆ gunfire       ┆ and 10+      ┆ tbreaking.   ┆              ┆ incident     │
│            ┆         ┆ terror attack ┆ injured. The ┆ My           ┆              ┆ related to   │
│            ┆         ┆ near          ┆ scene is     ┆ condolences  ┆              ┆ the          │
│            ┆         ┆ Jerusalem     ┆ still        ┆ to the       ┆              ┆ conflict,    │
│            ┆         ┆               ┆ on-going and ┆ victims'     ┆              ┆ which        │
│            ┆         ┆               ┆ getting      ┆ friends and  ┆              ┆ reflects a   │
│            ┆         ┆               ┆ udpated.     ┆ families.    ┆              ┆ personal     │
│            ┆         ┆               ┆              ┆              ┆              ┆ reaction to  │
│            ┆         ┆               ┆ Hebrew       ┆              ┆              ┆ the ongoing  │
│            ┆         ┆               ┆ sources:     ┆              ┆              ┆ situation in │
│            ┆         ┆               ┆              ┆              ┆              ┆ the region.  │
│            ┆         ┆               ┆ [Mako](https ┆              ┆              ┆              │
│            ┆         ┆               ┆ ://www.mako. ┆              ┆              ┆              │
│            ┆         ┆               ┆ co.il/news-m ┆              ┆              ┆              │
│            ┆         ┆               ┆ ilitary/2025 ┆              ┆              ┆              │
│            ┆         ┆               ┆ _q3/Article- ┆              ┆              ┆              │
│            ┆         ┆               ┆ f7e0d9d43282 ┆              ┆              ┆              │
│            ┆         ┆               ┆ 991027.htm)  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ [Ynet](https ┆              ┆              ┆              │
│            ┆         ┆               ┆ ://www.ynet. ┆              ┆              ┆              │
│            ┆         ┆               ┆ co.il/news/a ┆              ┆              ┆              │
│            ┆         ┆               ┆ rticle/hjclq ┆              ┆              ┆              │
│            ┆         ┆               ┆ zhcel)       ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ [Kan](https: ┆              ┆              ┆              │
│            ┆         ┆               ┆ //www.kan.or ┆              ┆              ┆              │
│            ┆         ┆               ┆ g.il/content ┆              ┆              ┆              │
│            ┆         ┆               ┆ /kan-news/de ┆              ┆              ┆              │
│            ┆         ┆               ┆ fense/949194 ┆              ┆              ┆              │
│            ┆         ┆               ┆ /)           ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ English      ┆              ┆              ┆              │
│            ┆         ┆               ┆ sources:     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ [Times of    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel](http ┆              ┆              ┆              │
│            ┆         ┆               ┆ s://www.time ┆              ┆              ┆              │
│            ┆         ┆               ┆ sofisrael.co ┆              ┆              ┆              │
│            ┆         ┆               ┆ m/liveblog_e ┆              ┆              ┆              │
│            ┆         ┆               ┆ ntry/shootin ┆              ┆              ┆              │
│            ┆         ┆               ┆ g-reported-a ┆              ┆              ┆              │
│            ┆         ┆               ┆ t-ramot-junc ┆              ┆              ┆              │
│            ┆         ┆               ┆ tion-entranc ┆              ┆              ┆              │
│            ┆         ┆               ┆ e-to-jerusal ┆              ┆              ┆              │
│            ┆         ┆               ┆ em/)         ┆              ┆              ┆              │
│ oaelbxl    ┆ 1rszuct ┆ "Israelis" in ┆              ┆ complete     ┆ 4            ┆ The comment  │
│            ┆         ┆ the West Bank ┆              ┆ sickos       ┆              ┆ expresses a  │
│            ┆         ┆ attack        ┆              ┆              ┆              ┆ negative     │
│            ┆         ┆ Palestinian   ┆              ┆              ┆              ┆ sentiment    │
│            ┆         ┆ fast food     ┆              ┆              ┆              ┆ towards the  │
│            ┆         ┆ workers, who  ┆              ┆              ┆              ┆ actions of   │
│            ┆         ┆ make their    ┆              ┆              ┆              ┆ Israelis in  │
│            ┆         ┆ food, for     ┆              ┆              ┆              ┆ the West     │
│            ┆         ┆ being Arabs   ┆              ┆              ┆              ┆ Bank, which  │
│            ┆         ┆               ┆              ┆              ┆              ┆ relates to   │
│            ┆         ┆               ┆              ┆              ┆              ┆ the broader  │
│            ┆         ┆               ┆              ┆              ┆              ┆ context of   │
│            ┆         ┆               ┆              ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆              ┆              ┆              ┆ the          │
│            ┆         ┆               ┆              ┆              ┆              ┆ treatment of │
│            ┆         ┆               ┆              ┆              ┆              ┆ Palestinians │
│            ┆         ┆               ┆              ┆              ┆              ┆ .            │
│ o9gyifr    ┆ 1rovyj0 ┆ Why is Iran   ┆ Since the    ┆ The oil      ┆ 4            ┆ The comment  │
│            ┆         ┆ bombing       ┆ war started, ┆ refineries   ┆              ┆ discusses    │
│            ┆         ┆ civilian      ┆ Iran has     ┆ are an       ┆              ┆ Iran's       │
│            ┆         ┆ targets in    ┆ been using   ┆ economic     ┆              ┆ military     │
│            ┆         ┆ friendly      ┆ missiles and ┆ tool. The    ┆              ┆ actions and  │
│            ┆         ┆ countries?    ┆ drones       ┆ airport in   ┆              ┆ their        │
│            ┆         ┆               ┆ against      ┆ Dubai hosts  ┆              ┆ implications │
│            ┆         ┆               ┆ civilian     ┆ USAF         ┆              ┆ for the Gulf │
│            ┆         ┆               ┆ targets in   ┆ satellite    ┆              ┆ states and   │
│            ┆         ┆               ┆ neighboring  ┆ infrastructu ┆              ┆ Israel,      │
│            ┆         ┆               ┆ countries.   ┆ re and C&C.  ┆              ┆ which are    │
│            ┆         ┆               ┆ They've hit  ┆ Some US      ┆              ┆ directly     │
│            ┆         ┆               ┆ a hotel in   ┆ military     ┆              ┆ related to   │
│            ┆         ┆               ┆ Bahrain, a   ┆ personnel    ┆              ┆ the broader  │
│            ┆         ┆               ┆ residential  ┆ has moved    ┆              ┆ context of   │
│            ┆         ┆               ┆ neighborhood ┆ from their   ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ in Saudi     ┆ bases into   ┆              ┆ conflict and │
│            ┆         ┆               ┆ Arabia, the  ┆ civilian     ┆              ┆ its regional │
│            ┆         ┆               ┆ airport in   ┆ buildings    ┆              ┆ impact.      │
│            ┆         ┆               ┆ Dubai, and   ┆ like the     ┆              ┆              │
│            ┆         ┆               ┆ others. Even ┆ apartment    ┆              ┆              │
│            ┆         ┆               ┆ desalinizati ┆ building     ┆              ┆              │
│            ┆         ┆               ┆ on plants,   ┆ that got     ┆              ┆              │
│            ┆         ┆               ┆ which some   ┆ droned which ┆              ┆              │
│            ┆         ┆               ┆ countries    ┆ hosted fleet ┆              ┆              │
│            ┆         ┆               ┆ depend on    ┆ command      ┆              ┆              │
│            ┆         ┆               ┆ for          ┆ personnel    ┆              ┆              │
│            ┆         ┆               ┆ survival.    ┆ and the      ┆              ┆              │
│            ┆         ┆               ┆              ┆ mainstream   ┆              ┆              │
│            ┆         ┆               ┆ I can see    ┆ media is     ┆              ┆              │
│            ┆         ┆               ┆ why they'd   ┆ speculating  ┆              ┆              │
│            ┆         ┆               ┆ shoot at     ┆ that certain ┆              ┆              │
│            ┆         ┆               ┆ Israel or at ┆ other        ┆              ┆              │
│            ┆         ┆               ┆ American     ┆ buildings    ┆              ┆              │
│            ┆         ┆               ┆ bases in     ┆ hosted       ┆              ┆              │
│            ┆         ┆               ┆ Gulf         ┆ intelligence ┆              ┆              │
│            ┆         ┆               ┆ countries.   ┆ operations   ┆              ┆              │
│            ┆         ┆               ┆ But why so   ┆              ┆              ┆              │
│            ┆         ┆               ┆ many         ┆ However the  ┆              ┆              │
│            ┆         ┆               ┆ civilian     ┆ over arching ┆              ┆              │
│            ┆         ┆               ┆ targets in   ┆ idea is to   ┆              ┆              │
│            ┆         ┆               ┆ countries    ┆ make this    ┆              ┆              │
│            ┆         ┆               ┆ that are not ┆ war as       ┆              ┆              │
│            ┆         ┆               ┆ involved in  ┆ economically ┆              ┆              │
│            ┆         ┆               ┆ the war and  ┆ costly to    ┆              ┆              │
│            ┆         ┆               ┆ are the      ┆ the gulf     ┆              ┆              │
│            ┆         ┆               ┆ closest      ┆ states,      ┆              ┆              │
│            ┆         ┆               ┆ thing Iran   ┆ Israel and   ┆              ┆              │
│            ┆         ┆               ┆ has to       ┆ US that any  ┆              ┆              │
│            ┆         ┆               ┆ allies?      ┆ victory ends ┆              ┆              │
│            ┆         ┆               ┆              ┆ up being     ┆              ┆              │
│            ┆         ┆               ┆              ┆ pyrrhic      ┆              ┆              │
│ nb5u7op    ┆ 1n0ppk8 ┆ Poll:  41% of ┆              ┆ The other    ┆ 4            ┆ The comment  │
│            ┆         ┆ Americans say ┆              ┆ 59% are      ┆              ┆ addresses    │
│            ┆         ┆ 'Israel IS    ┆              ┆ willfully    ┆              ┆ public       │
│            ┆         ┆ committing    ┆              ┆ ignorant or  ┆              ┆ opinion      │
│            ┆         ┆ Genocidal     ┆              ┆ complicit    ┆              ┆ regarding    │
│            ┆         ┆ Acts in Gaza' ┆              ┆              ┆              ┆ Israel's     │
│            ┆         ┆               ┆              ┆              ┆              ┆ actions in   │
│            ┆         ┆               ┆              ┆              ┆              ┆ Gaza,        │
│            ┆         ┆               ┆              ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆              ┆              ┆              ┆ relating to  │
│            ┆         ┆               ┆              ┆              ┆              ┆ the ongoing  │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆              ┆              ┆              ┆ the          │
│            ┆         ┆               ┆              ┆              ┆              ┆ perception   │
│            ┆         ┆               ┆              ┆              ┆              ┆ of genocide, │
│            ┆         ┆               ┆              ┆              ┆              ┆ which is a   │
│            ┆         ┆               ┆              ┆              ┆              ┆ core aspect  │
│            ┆         ┆               ┆              ┆              ┆              ┆ of the       │
│            ┆         ┆               ┆              ┆              ┆              ┆ discussion.  │
│ …          ┆ …       ┆ …             ┆ …            ┆ …            ┆ …            ┆ …            │
│ n3o27ca    ┆ 1m2chzb ┆ Nobody really ┆ Nobody       ┆ Israel can   ┆ 4            ┆ The comment  │
│            ┆         ┆ cares about   ┆ really cares ┆ not exist    ┆              ┆ expresses a  │
│            ┆         ┆ genocide.     ┆ about the    ┆ and the      ┆              ┆ strong       │
│            ┆         ┆               ┆ what is      ┆ world would  ┆              ┆ opinion      │
│            ┆         ┆               ┆ happening in ┆ be a better  ┆              ┆ about        │
│            ┆         ┆               ┆ Gaza. If     ┆ place.       ┆              ┆ Israel's     │
│            ┆         ┆               ┆ anyone       ┆              ┆              ┆ existence    │
│            ┆         ┆               ┆ really cared ┆              ┆              ┆ and implies  │
│            ┆         ┆               ┆ about        ┆              ┆              ┆ that the     │
│            ┆         ┆               ┆ genocide,    ┆              ┆              ┆ world would  │
│            ┆         ┆               ┆ they would   ┆              ┆              ┆ benefit from │
│            ┆         ┆               ┆ also care    ┆              ┆              ┆ its absence, │
│            ┆         ┆               ┆ about the    ┆              ┆              ┆ which        │
│            ┆         ┆               ┆ starving     ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆ children in  ┆              ┆              ┆ relates to   │
│            ┆         ┆               ┆ Africa who   ┆              ┆              ┆ the ongoing  │
│            ┆         ┆               ┆ are dying by ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆ the tens of  ┆              ┆              ┆ public       │
│            ┆         ┆               ┆ millions,    ┆              ┆              ┆ sentiment    │
│            ┆         ┆               ┆ about the    ┆              ┆              ┆ regarding    │
│            ┆         ┆               ┆ hundreds of  ┆              ┆              ┆ Israel and   │
│            ┆         ┆               ┆ thousands    ┆              ┆              ┆ Gaza.        │
│            ┆         ┆               ┆ killed in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the Sudanese ┆              ┆              ┆              │
│            ┆         ┆               ┆ war, and a   ┆              ┆              ┆              │

In [34]:
processed_df_filtered.filter(
    pl.col('comment_id').is_in(comment_ids),
    pl.col('content_relevance_score') == 5
    )['comment_id'].to_list()

['mz8ans8',
 'mtrkdzf',
 'njdvcit',
 'nsz6783',
 'n27i0kt',
 'nfgcrg1',
 'my7v96k',
 'nvpu8hc',
 'mziz50p',
 'nitry3y',
 'ntck9ht',
 'n9fqfdz']