In [14]:
import os
import polars as pl
import numpy as np

In [15]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
feature_data_dir = os.path.join(project_path, 'data', 'features')
raw_embeddings_path = os.path.join(feature_data_dir, 'embeddings.parquet')

In [19]:
df_raw_embeddings = pl.read_parquet(raw_embeddings_path)
df_raw_embeddings

shape: (89_063, 2)
┌────────────┬─────────────────────────────────┐
│ comment_id ┆ raw_embedding                   │
│ ---        ┆ ---                             │
│ str        ┆ list[f64]                       │
╞════════════╪═════════════════════════════════╡
│ my7m6yl    ┆ [-0.016144, -0.042267, … 0.023… │
│ mvnibgf    ┆ [-0.003933, -0.030396, … 0.016… │
│ n7k0beo    ┆ [0.020416, 0.018311, … 0.02380… │
│ nkaouem    ┆ [-0.019852, -0.001386, … 0.034… │
│ ni7idwb    ┆ [0.013649, 0.01326, … 0.02005]  │
│ …          ┆ …                               │
│ n3cbxh9    ┆ [-0.005898, -0.028656, … 0.044… │
│ muisbwh    ┆ [0.01593, -0.013954, … 0.02514… │
│ nhg5kt8    ┆ [-0.015251, 0.018234, … -0.004… │
│ n0mx6t1    ┆ [-0.009399, -0.009178, … 0.021… │
│ n8k5qp6    ┆ [-0.008347, -0.008904, … 0.030… │
└────────────┴─────────────────────────────────┘

In [20]:
df_raw_embeddings['comment_id'].unique()

shape: (86_921,)
Series: 'comment_id' [str]
[
	"nyef86o"
	"nq0zqxg"
	"mu3uwxg"
	"n19nt4p"
	"n5ac296"
	…
	"mucw7vs"
	"nhzxanl"
	"nas3qvp"
	"mynzrym"
	"mtmlo1c"
]

In [17]:
embedding_matrix = np.array(df_raw_embeddings['raw_embedding'].to_list())
embedding_matrix

array([[-0.0161438 , -0.04226685, -0.00683212, ..., -0.0114975 ,
         0.00370216,  0.02348328],
       [-0.00393295, -0.03039551, -0.01591492, ..., -0.01850891,
        -0.00619507,  0.01647949],
       [ 0.02041626,  0.01831055, -0.01309967, ..., -0.01243591,
        -0.01748657,  0.02380371],
       ...,
       [-0.01525116,  0.01823425,  0.00217438, ..., -0.01165009,
        -0.01216888, -0.00478745],
       [-0.00939941, -0.00917816, -0.013237  , ..., -0.00418472,
        -0.00115585,  0.02197266],
       [-0.00834656, -0.0089035 ,  0.00333023, ..., -0.00605774,
        -0.01069641,  0.03071594]], shape=(89063, 3072))

In [18]:
embedding_matrix.shape

(89063, 3072)