In [12]:
import os
import polars as pl

In [13]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
feature_data_dir = os.path.join(project_path, 'data', 'features')
embeddings_pca_path = os.path.join(feature_data_dir, 'embeddings_pca.parquet')

In [14]:
df_embeddings_pca = pl.read_parquet(embeddings_pca_path)
df_embeddings_pca

shape: (89_063, 51)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ comment_i ┆ embedding ┆ embedding ┆ embedding ┆ … ┆ embedding ┆ embedding ┆ embedding ┆ embeddin │
│ d         ┆ _pca_01   ┆ _pca_02   ┆ _pca_03   ┆   ┆ _pca_47   ┆ _pca_48   ┆ _pca_49   ┆ g_pca_50 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ my7m6yl   ┆ -0.269439 ┆ 0.018552  ┆ -0.018241 ┆ … ┆ -0.061168 ┆ 0.034038  ┆ -0.022932 ┆ 0.078731 │
│ mvnibgf   ┆ -0.037696 ┆ -0.105639 ┆ -0.156318 ┆ … ┆ -0.026709 ┆ -0.055402 ┆ -0.08528  ┆ -0.01276 │
│ n7k0beo   ┆ 0.212312  ┆ -0.185986 ┆ -0.093164 ┆ … ┆ -0.072945 ┆ 0.00377   ┆ -0.019508 ┆ 0.00401  │
│ nkaouem   ┆ 0.099984  ┆ -0.392803 ┆ 0.089627  ┆ … ┆ -0.042834 ┆ 0.013852  ┆ 0.032043  ┆ -0.04846 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ ni7idwb   ┆ 0.175958  ┆ 0.165412  ┆ -0.072269 ┆ … ┆ -0.03052  ┆ 0.045421  ┆ 0.042135  ┆ 0.059367 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ n3cbxh9   ┆ -0.030704 ┆ -0.183306 ┆ -0.239297 ┆ … ┆ -0.031602 ┆ 0.010375  ┆ 0.018445  ┆ -0.02032 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ muisbwh   ┆ -0.29761  ┆ 0.14492   ┆ 0.047793  ┆ … ┆ 0.073031  ┆ -0.051532 ┆ 0.060428  ┆ 0.014757 │
│ nhg5kt8   ┆ 0.278636  ┆ 0.100079  ┆ -0.00531  ┆ … ┆ 0.049143  ┆ 0.084964  ┆ -0.029014 ┆ 0.103523 │
│ n0mx6t1   ┆ 0.122749  ┆ 0.186238  ┆ -0.066632 ┆ … ┆ -0.013493 ┆ -0.01915  ┆ 0.081923  ┆ -0.00627 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ n8k5qp6   ┆ 0.202336  ┆ -0.02134  ┆ 0.131715  ┆ … ┆ 0.060825  ┆ 0.024229  ┆ 0.007808  ┆ 0.054835 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
df_embeddings_pca.shape

(89063, 51)

In [17]:
df_embeddings_pca['comment_id'].unique()

shape: (86_921,)
Series: 'comment_id' [str]
[
	"n9cp3bd"
	"n948lap"
	"n9cfcxi"
	"njcc9us"
	"nsllb2p"
	…
	"nc938lw"
	"mvtqhya"
	"mu3yk2g"
	"myegy37"
	"mvm7utr"
]