In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
raw_data_dir = os.path.join(project_path, 'data', 'raw_data')

In [3]:
raw_data = {}
for raw_data_name in os.listdir(raw_data_dir):
    raw_data_path = os.path.join(raw_data_dir, raw_data_name)
    raw_data[raw_data_name.split('.')[0]] = pl.read_parquet(raw_data_path)

In [4]:
post_raw_data_list = [raw_data[k] for k in raw_data.keys() if 'posts' in k]
comments_raw_data_list = [raw_data[k] for k in raw_data.keys() if 'comments' in k]

post_raw_data = pl.concat(post_raw_data_list, how='vertical')
comments_raw_data = pl.concat(comments_raw_data_list, how='vertical')

In [5]:
post_raw_data.head()

shape: (5, 13)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ post_id ┆ post_subre ┆ post_titl ┆ post_body ┆ … ┆ post_url  ┆ extractio ┆ extractio ┆ extractio │
│ ---     ┆ ddit       ┆ e         ┆ ---       ┆   ┆ ---       ┆ n_query   ┆ n_sort    ┆ n_time    │
│ str     ┆ ---        ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ str        ┆ str       ┆           ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1pkok6a ┆ Palestine  ┆ Tucker    ┆           ┆ … ┆ https://v ┆ ((gaza OR ┆ relevance ┆ 2025-12-2 │
│         ┆            ┆ Carlson   ┆           ┆   ┆ .redd.it/ ┆ palestine ┆           ┆ 2T22:24:5 │
│         ┆            ┆ visits    ┆           ┆   ┆ dzk705ax1 ┆ *) AND    ┆           ┆ 5.794505+ │
│         ┆            ┆ with Pal… ┆           ┆   ┆ r6g…      ┆ (gen…     ┆           ┆ 00:…      │
│ 1o0a7ao ┆ Palestine  ┆ There is  ┆           ┆ … ┆ https://i ┆ ((gaza OR ┆ relevance ┆ 2025-12-2 │
│         ┆            ┆ not a     ┆           ┆   ┆ .redd.it/ ┆ palestine ┆           ┆ 2T22:24:5 │
│         ┆            ┆ single    ┆           ┆   ┆ 48i5kp68u ┆ *) AND    ┆           ┆ 5.794505+ │
│         ┆            ┆ day in t… ┆           ┆   ┆ ntf…      ┆ (gen…     ┆           ┆ 00:…      │
│ 1myo0tv ┆ Palestine  ┆ Count all ┆           ┆ … ┆ https://i ┆ ((gaza OR ┆ relevance ┆ 2025-12-2 │
│         ┆            ┆ the IDF   ┆           ┆   ┆ .redd.it/ ┆ palestine ┆           ┆ 2T22:24:5 │
│         ┆            ┆ in Gaza   ┆           ┆   ┆ qhwi2exqs ┆ *) AND    ┆           ┆ 5.794505+ │
│         ┆            ┆ atta…     ┆           ┆   ┆ wkf…      ┆ (gen…     ┆           ┆ 00:…      │
│ 1mjswu6 ┆ Palestine  ┆ Dr.       ┆           ┆ … ┆ https://i ┆ ((gaza OR ┆ relevance ┆ 2025-12-2 │
│         ┆            ┆ Deirdre   ┆           ┆   ┆ .redd.it/ ┆ palestine ┆           ┆ 2T22:24:5 │
│         ┆            ┆ Nunan     ┆           ┆   ┆ tcyc0cdan ┆ *) AND    ┆           ┆ 5.794505+ │
│         ┆            ┆ went from ┆           ┆   ┆ jhf…      ┆ (gen…     ┆           ┆ 00:…      │
│         ┆            ┆ wo…       ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1oj3qcc ┆ Palestine  ┆ Gaza      ┆ [Source]( ┆ … ┆ https://i ┆ ((gaza OR ┆ relevance ┆ 2025-12-2 │
│         ┆            ┆ genocide: ┆ https://w ┆   ┆ .redd.it/ ┆ palestine ┆           ┆ 2T22:24:5 │
│         ┆            ┆ A crime   ┆ ww.ohchr. ┆   ┆ zp089rsrs ┆ *) AND    ┆           ┆ 5.794505+ │
│         ┆            ┆ Israel …  ┆ org…      ┆   ┆ 1yf…      ┆ (gen…     ┆           ┆ 00:…      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
comments_raw_data.head()

shape: (5, 6)
┌────────────┬─────────┬───────────────────┬───────────────┬───────────────────┬───────────────────┐
│ comment_id ┆ post_id ┆ comment_body      ┆ comment_score ┆ comment_created_u ┆ comment_created_d │
│ ---        ┆ ---     ┆ ---               ┆ ---           ┆ tc                ┆ ate               │
│ str        ┆ str     ┆ str               ┆ i64           ┆ ---               ┆ ---               │
│            ┆         ┆                   ┆               ┆ f64               ┆ str               │
╞════════════╪═════════╪═══════════════════╪═══════════════╪═══════════════════╪═══════════════════╡
│ ntmg7d9    ┆ 1pkok6a ┆ #                 ┆ 1             ┆ 1.7655e9          ┆ 2025-12-12T10:24: │
│            ┆         ┆ #                 ┆               ┆                   ┆ 18+00:00          │
│            ┆         ┆ Help Palestinians ┆               ┆                   ┆                   │
│            ┆         ┆ in need …         ┆               ┆                   ┆                   │
│ nton35x    ┆ 1pkok6a ┆ I watched this    ┆ 13            ┆ 1.7656e9          ┆ 2025-12-12T18:10: │
│            ┆         ┆ interview with …  ┆               ┆                   ┆ 39+00:00          │
│ ntmh1r0    ┆ 1pkok6a ┆ It's always weird ┆ 361           ┆ 1.7655e9          ┆ 2025-12-12T10:32: │
│            ┆         ┆ to find myse…     ┆               ┆                   ┆ 20+00:00          │
│ ntmhe8c    ┆ 1pkok6a ┆ Carlson is part   ┆ 128           ┆ 1.7655e9          ┆ 2025-12-12T10:35: │
│            ┆         ┆ of a long-runn…   ┆               ┆                   ┆ 40+00:00          │
│ ntmnup4    ┆ 1pkok6a ┆ I still hate him  ┆ 41            ┆ 1.7655e9          ┆ 2025-12-12T11:33: │
│            ┆         ┆ and his overa…    ┆               ┆                   ┆ 34+00:00          │
└────────────┴─────────┴───────────────────┴───────────────┴───────────────────┴───────────────────┘

In [7]:
post_raw_data.shape

(13332, 13)

In [8]:
comments_raw_data.shape

(868210, 6)

---

In [22]:
post_id = '1knnuln'
post_data = post_raw_data.filter(pl.col('post_id') == post_id)
post_title = post_data['post_title'][0]
post_body = post_data['post_body'][0]
post_url = post_data['post_url'][0]

In [23]:
print(post_title)

I asked it before but where the fuck is the media presenting an alternative vision to this right-wing blitz?

In [24]:
print(post_body)

The right wing have their media army, conditioning their followers with buzzwords like "critical thinking" and "DEI," but everything Trump is doing is like a direct attack on everything it means to be American, where is the media that actually outlines this? Or the importance of our system of government? The importance of checks and balances?

I can almost understand why low-information people get seduced by right wing media, there simply is no other media source in 2025 that educates viewers or readers on the mythology of this country.

I mean, I guess I'm just remembering things I read as a kid, like the whole "streets are paved in gold" thing, and bygone talking points about our country from generations past. But I don't hear these viewpoints anywhere, touting the true goodness of this country and its shared heritage. The creation of the national parks, defending democracy in WW2, the importance of things like due process or an independent judiciary... I swear when I was a kid in the 1990s there were widely spread talking points around these things. It was more baked in to the collective consciousness the importance of democratic values.

But I don't hear these perspectives anymore, from either side. For something to get into the collective consciousness and battle the right wing doublethink onslaught, it has to be readily available for people to watch again and again. Tucker Carlson's spinning his narrative night after night, so are many other shock jock-level news entertainers who are selling out the delicate soft power and shared culture of this country's governance.

But is there anyone left who actually feels a shred of genuine patriotism over our democratic values and shared history? Where are these media sources that talk about *why* the things that are being cut and destroyed are important, and why we'll miss them later?

I've looked through liberal sources (am proud liberal who just doesn't watch much political news anymore) and all I really see is people reacting to conservatives, or maybe wringing their hands about Palestine, a country that is NOT the United States. Is *anyone* actually talking in mass media, night after night, about the promise of this country, of what is possible with effective government?

Has the whole political debate shrunk down to literally just "let's destroy ourselves" vs "let's only destroy ourselves a little bit"?? Is no one with a megaphone really advancing a *positive* perspective of how the economy could work better for average people, or the benefits of investing in single payer healthcare and infrastructure? Or why it's a bad thing to cut the EPA? Or the importance of limiting corruption because a lot of our financial reputation is staked on being a low-corruption country with strong property rights? Does anyone actually fucking understand how this country works? I feel like I'm surrounded by shortsighted, easily misled morons.

In [25]:
print(post_url)

https://www.reddit.com/r/Liberal/comments/1knnuln/i_asked_it_before_but_where_the_fuck_is_the_media/

In [26]:
post_id = '1o5fc5m'
post_data = post_raw_data.filter(pl.col('post_id') == post_id)
post_title = post_data['post_title'][0]
post_body = post_data['post_body'][0]
post_url = post_data['post_url'][0]

In [27]:
print(post_title)

Hamas hands over all remaining hostages to Israel, Trump says Gaza war over

In [28]:
print(post_body)

In [29]:
print(post_url)

https://www.reuters.com/world/middle-east/israelis-honour-trump-hostages-return-home-two-years-after-their-capture-2025-10-12/

In [30]:
post_id = '1knnuln'
comment_id = 'msjrnde'
comment_data = comments_raw_data.filter(pl.col('post_id') == post_id, pl.col('comment_id') == comment_id)
comment_body = comment_data['comment_body'][0]

In [31]:
print(comment_body)

The media is not and never will be liberal. We see what they want us to see and they don’t have the same agenda as us(looking at you Reddit, does anyone on the right even know what’s happening right now, or do they just get kitty videos?)