In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
features_dir = os.path.join(project_path, 'data', 'features')
feature_file_path = os.path.join(features_dir, 'content_relevance_score.parquet')
feature_df = pl.read_parquet(feature_file_path)

In [3]:
feature_df

shape: (50, 3)
┌────────────┬─────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ content_relevance_score ┆ reasoning_content_relevance_sc… │
│ ---        ┆ ---                     ┆ ---                             │
│ str        ┆ i64                     ┆ str                             │
╞════════════╪═════════════════════════╪═════════════════════════════════╡
│ mc4kjv2    ┆ 5                       ┆ The comment discusses Israel i… │
│ mxpwqyc    ┆ 4                       ┆ The comment addresses the orig… │
│ no0v5r6    ┆ 0                       ┆ The comment is an automated bo… │
│ mbg5bt9    ┆ 1                       ┆ The comment does not directly … │
│ n0ya0fv    ┆ 5                       ┆ The comment discusses the ceas… │
│ …          ┆ …                       ┆ …                               │
│ nrqycyr    ┆ 3                       ┆ The comment discusses the impa… │
│ ner2zhb    ┆ 4                       ┆ The comment references discuss… │
│ nfxfpok    ┆ 4                       ┆ The comment reflects a sarcast… │
│ n8c723m    ┆ 5                       ┆ The comment discusses the impa… │
│ nee03xs    ┆ 2                       ┆ The comment discusses religiou… │
└────────────┴─────────────────────────┴─────────────────────────────────┘

In [4]:
feature_df['content_relevance_score'].value_counts().sort('count', descending=True)

shape: (6, 2)
┌─────────────────────────┬───────┐
│ content_relevance_score ┆ count │
│ ---                     ┆ ---   │
│ i64                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ 5                       ┆ 17    │
│ 4                       ┆ 16    │
│ 3                       ┆ 5     │
│ 1                       ┆ 5     │
│ 2                       ┆ 4     │
│ 0                       ┆ 3     │
└─────────────────────────┴───────┘

In [5]:
count_relevant_content = sum(feature_df['content_relevance_score'] >= 3) 
content_size = len(feature_df)
prop_relevant_content = count_relevant_content / content_size
print(f"Count relevant content: {count_relevant_content}")
print(f"Percentage relevant content: {round(prop_relevant_content * 100, 2)}%")

Count relevant content: 38
Percentage relevant content: 76.0%