In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
features_dir = os.path.join(project_path, 'data', 'features')
feature_file_path = os.path.join(features_dir, 'content_relevance_score.parquet')
feature_df = pl.read_parquet(feature_file_path)

In [3]:
feature_df

shape: (50, 2)
┌────────────┬─────────────────────────┐
│ comment_id ┆ content_relevance_score │
│ ---        ┆ ---                     │
│ str        ┆ i64                     │
╞════════════╪═════════════════════════╡
│ nj9e8nu    ┆ 4                       │
│ njamm7j    ┆ 5                       │
│ n5wydap    ┆ 1                       │
│ njcmxi1    ┆ 2                       │
│ nja9atj    ┆ 1                       │
│ …          ┆ …                       │
│ nj93pa9    ┆ 0                       │
│ mww5ie9    ┆ 2                       │
│ n5xz7x2    ┆ 4                       │
│ nm5xh1u    ┆ 1                       │
│ njatgzx    ┆ 2                       │
└────────────┴─────────────────────────┘

In [4]:
feature_df['content_relevance_score'].value_counts()

shape: (5, 2)
┌─────────────────────────┬───────┐
│ content_relevance_score ┆ count │
│ ---                     ┆ ---   │
│ i64                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ 2                       ┆ 4     │
│ 4                       ┆ 12    │
│ 1                       ┆ 21    │
│ 5                       ┆ 9     │
│ 0                       ┆ 4     │
└─────────────────────────┴───────┘

In [5]:
sum(feature_df['content_relevance_score'] >= 3)

21

In [6]:
sum(feature_df['content_relevance_score'] >= 3) / len(feature_df)

0.42