In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
processed_data_dir = os.path.join(project_path, 'data', 'processed_data')
processed_data_path = os.path.join(processed_data_dir, '04d_processed_data.parquet')

In [3]:
processed_data = pl.read_parquet(processed_data_path)
processed_data.head()

shape: (5, 35)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ comment_id ┆ post_id ┆ comment_b ┆ comment_s ┆ … ┆ dominant_ ┆ raw_embed ┆ political ┆ sentiment │
│ ---        ┆ ---     ┆ ody       ┆ core      ┆   ┆ frame     ┆ ding      ┆ _stance   ┆ _score    │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ str       ┆ i64       ┆   ┆ str       ┆ list[f64] ┆ i64       ┆ f64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ njalw5c    ┆ 1o5fc5m ┆ Great     ┆ 3         ┆ … ┆ Geopoliti ┆ [0.029796 ┆ 2         ┆ -0.3      │
│            ┆         ┆ news, but ┆           ┆   ┆ cal/Polit ┆ , -0.0034 ┆           ┆           │
│            ┆         ┆ as long   ┆           ┆   ┆ ical      ┆ 91, …     ┆           ┆           │
│            ┆         ┆ as isr…   ┆           ┆   ┆           ┆ -0.015…   ┆           ┆           │
│ nm4anua    ┆ 1ojjtnz ┆ Oh I      ┆ 1         ┆ … ┆ Humanitar ┆ [0.003255 ┆ 2         ┆ 0.3       │
│            ┆         ┆ agree she ┆           ┆   ┆ ian/Legal ┆ ,         ┆           ┆           │
│            ┆         ┆ is bat    ┆           ┆   ┆           ┆ 0.008784, ┆           ┆           │
│            ┆         ┆ shit cra… ┆           ┆   ┆           ┆ …         ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆ -0.0008…  ┆           ┆           │
│ nja4ar2    ┆ 1o5fc5m ┆ Thousands ┆ 6         ┆ … ┆ Humanitar ┆ null      ┆ 2         ┆ -0.6      │
│            ┆         ┆ of the    ┆           ┆   ┆ ian/Legal ┆           ┆           ┆           │
│            ┆         ┆ detainees ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ are…      ┆           ┆   ┆           ┆           ┆           ┆           │
│ nm3pvch    ┆ 1ojjtnz ┆ No, most, ┆ 3         ┆ … ┆ Humanitar ┆ [0.014186 ┆ 3         ┆ 0.1       │
│            ┆         ┆ like      ┆           ┆   ┆ ian/Legal ┆ ,         ┆           ┆           │
│            ┆         ┆ myself,   ┆           ┆   ┆           ┆ 0.045343, ┆           ┆           │
│            ┆         ┆ scrutin…  ┆           ┆   ┆           ┆ …         ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆ 0.01733…  ┆           ┆           │
│ n5yci2x    ┆ 1mctwpa ┆ The Biden ┆ 27        ┆ … ┆ Humanitar ┆ null      ┆ 1         ┆ -0.8      │
│            ┆         ┆ administr ┆           ┆   ┆ ian/Legal ┆           ┆           ┆           │
│            ┆         ┆ ation was ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ c…        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
processed_data[['comment_id', 'post_id', 'text_content', 'argument_quality_score', 'discourse_tone', 'dominant_frame', 'political_stance', 'sentiment_score']]

shape: (23, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ comment_id ┆ post_id ┆ text_conte ┆ argument_q ┆ discourse_ ┆ dominant_f ┆ political ┆ sentiment │
│ ---        ┆ ---     ┆ nt         ┆ uality_sco ┆ tone       ┆ rame       ┆ _stance   ┆ _score    │
│ str        ┆ str     ┆ ---        ┆ re         ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆         ┆ str        ┆ ---        ┆ str        ┆ str        ┆ i64       ┆ f64       │
│            ┆         ┆            ┆ i64        ┆            ┆            ┆           ┆           │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ njalw5c    ┆ 1o5fc5m ┆ Post       ┆ 2          ┆ Analytical ┆ Geopolitic ┆ 2         ┆ -0.3      │
│            ┆         ┆ Title:     ┆            ┆            ┆ al/Politic ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆ al         ┆           ┆           │
│            ┆         ┆ Hamas      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ hands over ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ …          ┆            ┆            ┆            ┆           ┆           │
│ nm4anua    ┆ 1ojjtnz ┆ Post       ┆ 2          ┆ Sarcastic  ┆ Humanitari ┆ 2         ┆ 0.3       │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Marjorie   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Taylor G…  ┆            ┆            ┆            ┆           ┆           │
│ nja4ar2    ┆ 1o5fc5m ┆ Post       ┆ 3          ┆ Informativ ┆ Humanitari ┆ 2         ┆ -0.6      │
│            ┆         ┆ Title:     ┆            ┆ e          ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Hamas      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ hands over ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ …          ┆            ┆            ┆            ┆           ┆           │
│ nm3pvch    ┆ 1ojjtnz ┆ Post       ┆ 2          ┆ Analytical ┆ Humanitari ┆ 3         ┆ 0.1       │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Marjorie   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Taylor G…  ┆            ┆            ┆            ┆           ┆           │
│ n5yci2x    ┆ 1mctwpa ┆ Post       ┆ 2          ┆ Hostile    ┆ Humanitari ┆ 1         ┆ -0.8      │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ New poll   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ shows pl…  ┆            ┆            ┆            ┆           ┆           │
│ …          ┆ …       ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         │
│ n5y0puk    ┆ 1mctwpa ┆ Post       ┆ 1          ┆ Hostile    ┆ Security/M ┆ 4         ┆ -0.4      │
│            ┆         ┆ Title:     ┆            ┆            ┆ ilitary    ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ New poll   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ shows pl…  ┆            ┆            ┆            ┆           ┆           │
│ njaced6    ┆ 1o5fc5m ┆ Post       ┆ 3          ┆ Analytical ┆ Historical ┆ 2         ┆ -0.6      │
│            ┆         ┆ Title:     ┆            ┆            ┆ /Religious ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Hamas      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ hands over ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ …          ┆            ┆            ┆            ┆           ┆           │
│ njetwvu    ┆ 1o5fc5m ┆ Post       ┆ 1          ┆ Sarcastic  ┆ Geopolitic ┆ 4         ┆ -0.4      │
│            ┆         ┆ Title:     ┆            ┆            ┆ al/Politic ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆ al         ┆           ┆           │
│            ┆         ┆ Hamas      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ hands over ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ …          ┆            ┆            ┆            ┆           ┆           │
│ njamm7j    ┆ 1o5fc5m ┆ Post       ┆ 3          ┆ Hostile    ┆ Security/M ┆ 4         ┆ -0.8      │
│            ┆         ┆ Title:     ┆            ┆            ┆ ilitary    ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Hamas      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ hands over ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ …          ┆            ┆            ┆            ┆           ┆           │
│ nm3so23    ┆ 1ojjtnz ┆ Post       ┆ 1          ┆ Hostile    ┆ Humanitari ┆ 1         ┆ -0.9      │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Marjorie   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Taylor G…  ┆            ┆            ┆            ┆           ┆           │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘